/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Control.ActualizarCitas;
import Control.ControlCitas;
import Control.ControlGeneral;
import Control.ControlUsuarios;
import HISTORIA_CLINICA.*;
import Modelo.Usuario;
import Tabla.TablaAgendaDiaria;
import Utilidades.Utilidades;
import Utilidades.datosUsuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Acer
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    public Usuario usuario = null;
    public ArrayList<String[]> control = null;
    public ControlCitas cita = new ControlCitas();
    public ControlGeneral general = new ControlGeneral();
    public ArrayList<String[]> Lista_auxiliar = new ArrayList<>();
    public ArrayList<String[]> Lista_Diaria = new ArrayList<>();
    public ArrayList<String[]> Lista_Diaria_aux = new ArrayList<>();
    public ArrayList<String[]> Lista_Diaria_Nulo = new ArrayList<>();
    public DefaultTableModel modelo;
    private int x = 0, y = 0;
    public ventana venthc;

    public String[] nombreColumnas = new String[]{"Hora", "Paciente", "Motivo", "Estado", "Ag", "HC", "Fact"};
    public int b = 0;
    TablaAgendaDiaria tbl;
    public int bandhc;
    public String passdin = "";
    ActualizarCitas hilo = new ActualizarCitas(this);

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        bandhc = 0;
        Utilidades.EstablecerIcono(this);
        //CargarMenu();
        tbl = new TablaAgendaDiaria();
        OcultarMnConfig(false);
        btnAgenda.setPreferredSize(new java.awt.Dimension(69, 69));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMBasico = new javax.swing.JMenu();
        jMAgenda = new javax.swing.JMenu();
        jMDiasNulos = new javax.swing.JMenuItem();
        jMConfirmacion = new javax.swing.JMenuItem();
        jMPersonas = new javax.swing.JMenu();
        jMPaciente = new javax.swing.JMenuItem();
        jMPacAuxiliar = new javax.swing.JMenuItem();
        jMEmpleados = new javax.swing.JMenuItem();
        jMFacturacion = new javax.swing.JMenu();
        jMArticulo = new javax.swing.JMenuItem();
        jMConceptos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMUsuarios = new javax.swing.JMenuItem();
        jMInformes = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        AgendaDiaria = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgendaDiaria = new Tabla.DiarioTable(){

            public boolean isCellEditable(int rowindex, int colindex){
                return false;
            }

        };
        btnAgenda = new javax.swing.JButton();
        btnHistoriaClinica = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();
        Menu = new javax.swing.JPanel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        ConfiguracionUsuario = new javax.swing.JPanel();
        btnConfiguracion = new javax.swing.JButton();
        pnlConfig = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCambioPass = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblCerrarSesion = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pnlDiasNulos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlAgenda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnlConfirmacion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlPersonas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pnlPacientes = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlPacAuxiliar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnlPersonal = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlFacturacion = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnlArticulos = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnlConceptos = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        pnlAnfact = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        pnlUsuarios = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pnlInformes = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        jMBasico.setText("Basico");

        jMAgenda.setText("Agenda");

        jMDiasNulos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMDiasNulos.setText("Dias no laborales");
        jMDiasNulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDiasNulosActionPerformed(evt);
            }
        });
        jMAgenda.add(jMDiasNulos);

        jMConfirmacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMConfirmacion.setText("Confirmacion");
        jMConfirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConfirmacionActionPerformed(evt);
            }
        });
        jMAgenda.add(jMConfirmacion);

        jMBasico.add(jMAgenda);

        jMPersonas.setText("Personas");

        jMPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMPaciente.setText("Pacientes");
        jMPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPacienteActionPerformed(evt);
            }
        });
        jMPersonas.add(jMPaciente);

        jMPacAuxiliar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMPacAuxiliar.setText("Paciente Auxiliar");
        jMPacAuxiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPacAuxiliarActionPerformed(evt);
            }
        });
        jMPersonas.add(jMPacAuxiliar);

        jMEmpleados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMEmpleados.setText("Empleados");
        jMEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMEmpleadosActionPerformed(evt);
            }
        });
        jMPersonas.add(jMEmpleados);

        jMBasico.add(jMPersonas);

        jMFacturacion.setText("Facturación");

        jMArticulo.setText("Articulo");
        jMArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMArticuloActionPerformed(evt);
            }
        });
        jMFacturacion.add(jMArticulo);

        jMConceptos.setText("Conceptos");
        jMConceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConceptosActionPerformed(evt);
            }
        });
        jMFacturacion.add(jMConceptos);

        jMBasico.add(jMFacturacion);
        jMBasico.add(jSeparator1);

        jMUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMUsuarios.setText("Usuarios");
        jMUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMUsuariosActionPerformed(evt);
            }
        });
        jMBasico.add(jMUsuarios);

        jMenuBar1.add(jMBasico);

        jMInformes.setText("Informes");
        jMInformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMInformesMousePressed(evt);
            }
        });
        jMInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMInformesActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMInformes);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JAOS SYSTEM");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/Logo.jpg")));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 82, 118)));
        jPanel1.setPreferredSize(new java.awt.Dimension(876, 566));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgendaDiaria.setBackground(new java.awt.Color(255, 255, 255));

        tblAgendaDiaria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hora", "Paciente", "Motivo", "Estado", "Ag  ", "HC", "Fact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAgendaDiaria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblAgendaDiaria.getTableHeader().setReorderingAllowed(false);
        tblAgendaDiaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAgendaDiariaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAgendaDiaria);
        if (tblAgendaDiaria.getColumnModel().getColumnCount() > 0) {
            tblAgendaDiaria.getColumnModel().getColumn(0).setResizable(false);
            tblAgendaDiaria.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblAgendaDiaria.getColumnModel().getColumn(1).setResizable(false);
            tblAgendaDiaria.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblAgendaDiaria.getColumnModel().getColumn(2).setResizable(false);
            tblAgendaDiaria.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblAgendaDiaria.getColumnModel().getColumn(3).setResizable(false);
            tblAgendaDiaria.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblAgendaDiaria.getColumnModel().getColumn(4).setResizable(false);
            tblAgendaDiaria.getColumnModel().getColumn(4).setPreferredWidth(10);
            tblAgendaDiaria.getColumnModel().getColumn(5).setResizable(false);
            tblAgendaDiaria.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        javax.swing.GroupLayout AgendaDiariaLayout = new javax.swing.GroupLayout(AgendaDiaria);
        AgendaDiaria.setLayout(AgendaDiariaLayout);
        AgendaDiariaLayout.setHorizontalGroup(
            AgendaDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        AgendaDiariaLayout.setVerticalGroup(
            AgendaDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        jPanel1.add(AgendaDiaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 520, 520));

        btnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/agenda_1.png"))); // NOI18N
        btnAgenda.setBorderPainted(false);
        btnAgenda.setContentAreaFilled(false);
        btnAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgenda.setFocusPainted(false);
        btnAgenda.setFocusable(false);
        btnAgenda.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/agenda_2.png"))); // NOI18N
        btnAgenda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/agenda_2.png"))); // NOI18N
        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 164, 164));

        btnHistoriaClinica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/historiaclinica_1.png"))); // NOI18N
        btnHistoriaClinica.setBorderPainted(false);
        btnHistoriaClinica.setContentAreaFilled(false);
        btnHistoriaClinica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistoriaClinica.setFocusPainted(false);
        btnHistoriaClinica.setFocusable(false);
        btnHistoriaClinica.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/historiaclinica_2.png"))); // NOI18N
        btnHistoriaClinica.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/historiaclinica_2.png"))); // NOI18N
        btnHistoriaClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaClinicaActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistoriaClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 164, 164));

        btnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/facturacion_1.png"))); // NOI18N
        btnFactura.setBorderPainted(false);
        btnFactura.setContentAreaFilled(false);
        btnFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFactura.setFocusPainted(false);
        btnFactura.setFocusable(false);
        btnFactura.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/facturacion_2.png"))); // NOI18N
        btnFactura.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/facturacion_2.png"))); // NOI18N
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, 164, 164));

        Menu.setBackground(new java.awt.Color(41, 128, 185));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        Menu.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 460, 30));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        Menu.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 440, 35));

        ConfiguracionUsuario.setBackground(new java.awt.Color(41, 128, 185));
        ConfiguracionUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConfiguracionUsuarioMouseExited(evt);
            }
        });
        ConfiguracionUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfiguracion.setBackground(new java.awt.Color(255, 255, 255));
        btnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/abajo_1.png"))); // NOI18N
        btnConfiguracion.setBorder(null);
        btnConfiguracion.setBorderPainted(false);
        btnConfiguracion.setContentAreaFilled(false);
        btnConfiguracion.setFocusPainted(false);
        btnConfiguracion.setFocusable(false);
        btnConfiguracion.setMaximumSize(new java.awt.Dimension(50, 50));
        btnConfiguracion.setMinimumSize(new java.awt.Dimension(20, 20));
        btnConfiguracion.setPreferredSize(new java.awt.Dimension(35, 35));
        btnConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfiguracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfiguracionMouseExited(evt);
            }
        });
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });
        ConfiguracionUsuario.add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 30, 30));

        pnlConfig.setBackground(new java.awt.Color(255, 255, 255));
        pnlConfig.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, null));
        pnlConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlConfigMouseEntered(evt);
            }
        });
        pnlConfig.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlConfigMouseMoved(evt);
            }
        });
        pnlConfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(26, 82, 118));

        lblCambioPass.setBackground(new java.awt.Color(0, 0, 0));
        lblCambioPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCambioPass.setForeground(new java.awt.Color(234, 242, 248));
        lblCambioPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCambioPass.setText("Cambiar Contraseña  ");
        lblCambioPass.setAlignmentX(1.0F);
        lblCambioPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCambioPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCambioPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCambioPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCambioPassMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCambioPass, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCambioPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnlConfig.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jPanel3.setBackground(new java.awt.Color(26, 82, 118));

        lblCerrarSesion.setBackground(new java.awt.Color(0, 0, 0));
        lblCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(234, 242, 248));
        lblCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCerrarSesion.setText("Cerrar Sesión  ");
        lblCerrarSesion.setAlignmentX(1.0F);
        lblCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnlConfig.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 140, -1));

        ConfiguracionUsuario.add(pnlConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 60));

        Menu.add(ConfiguracionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 150, 110));

        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 41, 870, 110));

        jPanel4.setBackground(new java.awt.Color(26, 82, 118));

        pnlDiasNulos.setBackground(new java.awt.Color(26, 82, 118));
        pnlDiasNulos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    Días no Laborales");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        pnlDiasNulos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        pnlAgenda.setBackground(new java.awt.Color(15, 48, 69));
        pnlAgenda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("   Agenda");
        pnlAgenda.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/agenda_mini_1.png"))); // NOI18N
        pnlAgenda.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 30, 30));

        pnlConfirmacion.setBackground(new java.awt.Color(26, 82, 118));
        pnlConfirmacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlConfirmacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("    Confirmación");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        pnlConfirmacion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        pnlPersonas.setBackground(new java.awt.Color(15, 48, 69));
        pnlPersonas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("   Personas");
        pnlPersonas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/usuario_mini_1.png"))); // NOI18N
        pnlPersonas.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 30));

        pnlPacientes.setBackground(new java.awt.Color(26, 82, 118));
        pnlPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlPacientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("    Pacientes");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        pnlPacientes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        pnlPacAuxiliar.setBackground(new java.awt.Color(26, 82, 118));
        pnlPacAuxiliar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlPacAuxiliar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("    Paciente Auxiliar");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        pnlPacAuxiliar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        pnlPersonal.setBackground(new java.awt.Color(26, 82, 118));
        pnlPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("    Gestión de Personal");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        pnlPersonal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        pnlFacturacion.setBackground(new java.awt.Color(15, 48, 69));
        pnlFacturacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl.setForeground(new java.awt.Color(255, 255, 255));
        lbl.setText("   Facturación");
        pnlFacturacion.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_1.png"))); // NOI18N
        pnlFacturacion.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 30));

        pnlArticulos.setBackground(new java.awt.Color(26, 82, 118));
        pnlArticulos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlArticulos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("    Artículos");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        pnlArticulos.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        pnlConceptos.setBackground(new java.awt.Color(26, 82, 118));
        pnlConceptos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlConceptos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("    Conceptos");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });
        pnlConceptos.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        pnlAnfact.setBackground(new java.awt.Color(26, 82, 118));
        pnlAnfact.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlAnfact.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("    Anulación de Facturas");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23MouseExited(evt);
            }
        });
        pnlAnfact.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        pnlUsuarios.setBackground(new java.awt.Color(15, 48, 69));
        pnlUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("   Usuarios");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        pnlUsuarios.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/usuario_mini_1.png"))); // NOI18N
        pnlUsuarios.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 30, 30));

        pnlInformes.setBackground(new java.awt.Color(15, 48, 69));
        pnlInformes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("   Informes");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        pnlInformes.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/informes_mini_1.png"))); // NOI18N
        pnlInformes.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 30, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlDiasNulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlPacAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlConceptos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlAnfact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlInformes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlDiasNulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPacAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlConceptos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlAnfact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlInformes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 190, 660));

        jPanel17.setBackground(new java.awt.Color(26, 82, 118));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel17MousePressed(evt);
            }
        });
        jPanel17.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel17MouseDragged(evt);
            }
        });
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/cerrar_1.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel17.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 4, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/minimizar.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel17.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 4, -1, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Principal");
        jPanel17.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        if (usuario == null) {
//            new ventanainiciarsesion(this).setVisible(true);
//        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        hilo.terminar();
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void tblAgendaDiariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAgendaDiariaMouseClicked
        int fila = tblAgendaDiaria.getSelectedRow();
        int cola = tblAgendaDiaria.getSelectedColumn();
        String[] datos = getDatosxFila(fila);
        //System.out.println("dat-->" + datos);
        if (datos != null) {
            System.out.println("**********************************");
            for (String dat : datos) {
                System.out.println("dat-->" + dat);
            }
            System.out.println("**********************************");
            if (cola == 4) {//AGENDA
                System.out.println("ABRIR AGENDA");
                ///FILA  //PK_CITA, PAUX, ID, PACIENTE, HORA, ESTADO, NOMBRES, APELLIDOS
                new VentanaCitas(datos[3], datos[4], datos[2], datos[1], this).setVisible(true);
            } else if (cola == 5) {//HC 
                System.out.println("bandhc-->"+bandhc);
                if (bandhc == 0) {
                    venthc = new ventana(this, datos[3], datos[5], datos[6], datos[2], datos[1]);
                    venthc.setVisible(true);
                } else {
                    System.out.println("datos[2]---->"+datos[2]+"/////");
                    venthc.cargarHCDesdeAgendaDiaria(datos[3], datos[5], datos[6], datos[2], datos[1]);
                    venthc.setState(ventana.NORMAL);
                }
            } else if (cola == 6) {//FACT
                new ventanaConsultarF(datos[3], datos[5], datos[6], datos[2], datos[1]).setVisible(true);
            }
        }

    }//GEN-LAST:event_tblAgendaDiariaMouseClicked

    private void jMDiasNulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDiasNulosActionPerformed
        new VentanaDiasNulos().setVisible(true);
    }//GEN-LAST:event_jMDiasNulosActionPerformed

    private void jMPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPacienteActionPerformed
        new VistaPaciente(this).setVisible(true);
    }//GEN-LAST:event_jMPacienteActionPerformed

    private void jMPacAuxiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPacAuxiliarActionPerformed
        new VentanaPacienteAux(this).setVisible(true);
    }//GEN-LAST:event_jMPacAuxiliarActionPerformed

    private void jMEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMEmpleadosActionPerformed
        new VentanaPersonal(this).setVisible(true);
    }//GEN-LAST:event_jMEmpleadosActionPerformed

    private void jMConceptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConceptosActionPerformed
        new ventanaConsultarConcepto().setVisible(true);
    }//GEN-LAST:event_jMConceptosActionPerformed

    private void jMArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMArticuloActionPerformed
        new VentanaConsultarArticulo().setVisible(true);
    }//GEN-LAST:event_jMArticuloActionPerformed

    private void jMUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMUsuariosActionPerformed
        new VentanaUsuarios(this).setVisible(true);
    }//GEN-LAST:event_jMUsuariosActionPerformed

    private void jMConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConfirmacionActionPerformed
        new VentanaConfirmacion(this).setVisible(true);
    }//GEN-LAST:event_jMConfirmacionActionPerformed

    private void jMInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMInformesActionPerformed

    }//GEN-LAST:event_jMInformesActionPerformed

    private void jMInformesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMInformesMousePressed
        System.out.println("HOLA");
        new VentanaInformes().setVisible(true);
    }//GEN-LAST:event_jMInformesMousePressed

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed
        new VentanaCitas(this).setVisible(true);
    }//GEN-LAST:event_btnAgendaActionPerformed

    private void btnHistoriaClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaClinicaActionPerformed
        if (bandhc == 0) {
            venthc = new ventana(this);
            venthc.setVisible(true);
        } else {
            venthc.setState(ventana.NORMAL);
        }
    }//GEN-LAST:event_btnHistoriaClinicaActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        new ventanaConsultarF().setVisible(true);
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnConfiguracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiguracionMouseEntered
        //System.out.println("curioso-11->"+pnlConfig.);
        //        pnlConfig.setVisible(true);
    }//GEN-LAST:event_btnConfiguracionMouseEntered

    private void btnConfiguracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiguracionMouseExited
        //        System.out.println("curioso-->"+pnlConfig.getMousePosition());
        //        pnlConfig.setVisible(true);
    }//GEN-LAST:event_btnConfiguracionMouseExited

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed

        OcultarMnConfig(true);
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void lblCambioPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambioPassMouseClicked
        new VentanaContrasenia(lblUsuario.getText()).setVisible(true);
    }//GEN-LAST:event_lblCambioPassMouseClicked

    private void lblCambioPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambioPassMouseEntered
        jPanel2.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_lblCambioPassMouseEntered

    private void lblCambioPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambioPassMouseExited
        jPanel2.setBackground(new Color(26, 82, 118));
    }//GEN-LAST:event_lblCambioPassMouseExited

    private void lblCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseEntered
        jPanel3.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_lblCerrarSesionMouseEntered

    private void lblCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseExited
        jPanel3.setBackground(new Color(26, 82, 118));
    }//GEN-LAST:event_lblCerrarSesionMouseExited

    private void pnlConfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlConfigMouseEntered
        //        System.out.println("MouseEntered curioso-->"+pnlConfig.getMousePosition());
    }//GEN-LAST:event_pnlConfigMouseEntered

    private void pnlConfigMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlConfigMouseMoved
        //        System.out.println("MouseMoved curioso-->"+pnlConfig.getMousePosition());
    }//GEN-LAST:event_pnlConfigMouseMoved

    private void ConfiguracionUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfiguracionUsuarioMouseExited
        OcultarMnConfig(false);
    }//GEN-LAST:event_ConfiguracionUsuarioMouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        hilo.terminar();
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setState(VentanaPrincipal.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        pnlDiasNulos.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        pnlDiasNulos.setBackground(new Color(26, 82, 118));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        pnlConfirmacion.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        pnlConfirmacion.setBackground(new Color(26, 82, 118));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        pnlPacientes.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        pnlPacientes.setBackground(new Color(26, 82, 118));
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        pnlPacAuxiliar.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        pnlPacAuxiliar.setBackground(new Color(26, 82, 118));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        pnlPersonal.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        pnlPersonal.setBackground(new Color(26, 82, 118));
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        pnlArticulos.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        pnlArticulos.setBackground(new Color(26, 82, 118));
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new VentanaDiasNulos().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new VentanaConfirmacion(this).setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new VistaPaciente(this).setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        new VentanaPacienteAux(this).setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        new VentanaPersonal(this).setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        new VentanaConsultarArticulo().setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jPanel17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel17MousePressed

    private void jPanel17MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jPanel17MouseDragged

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        new VentanaUsuarios(this).setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        new VentanaInformes().setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        cerrarSesion();
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        new ventanaConsultarConcepto().setVisible(true);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        pnlConceptos.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        pnlConceptos.setBackground(new Color(26, 82, 118));
    }//GEN-LAST:event_jLabel21MouseExited

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        new VentanaAnularFactura(this).setVisible(true);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseEntered
        pnlAnfact.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_jLabel23MouseEntered

    private void jLabel23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseExited
        pnlAnfact.setBackground(new Color(26, 82, 118));
    }//GEN-LAST:event_jLabel23MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgendaDiaria;
    private javax.swing.JPanel ConfiguracionUsuario;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnHistoriaClinica;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMAgenda;
    private javax.swing.JMenuItem jMArticulo;
    private javax.swing.JMenu jMBasico;
    private javax.swing.JMenuItem jMConceptos;
    private javax.swing.JMenuItem jMConfirmacion;
    private javax.swing.JMenuItem jMDiasNulos;
    private javax.swing.JMenuItem jMEmpleados;
    private javax.swing.JMenu jMFacturacion;
    private javax.swing.JMenu jMInformes;
    private javax.swing.JMenuItem jMPacAuxiliar;
    private javax.swing.JMenuItem jMPaciente;
    private javax.swing.JMenu jMPersonas;
    private javax.swing.JMenuItem jMUsuarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblCambioPass;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlAgenda;
    private javax.swing.JPanel pnlAnfact;
    private javax.swing.JPanel pnlArticulos;
    private javax.swing.JPanel pnlConceptos;
    private javax.swing.JPanel pnlConfig;
    private javax.swing.JPanel pnlConfirmacion;
    private javax.swing.JPanel pnlDiasNulos;
    private javax.swing.JPanel pnlFacturacion;
    private javax.swing.JPanel pnlInformes;
    private javax.swing.JPanel pnlPacAuxiliar;
    private javax.swing.JPanel pnlPacientes;
    private javax.swing.JPanel pnlPersonal;
    private javax.swing.JPanel pnlPersonas;
    private javax.swing.JPanel pnlUsuarios;
    public javax.swing.JTable tblAgendaDiaria;
    // End of variables declaration//GEN-END:variables

    public void iniciarComponentes() {
        if (control != null) {
            lblUsuario.setText(control.get(0)[0]);
            lblNombreUsuario.setText(control.get(0)[3] + " " + control.get(0)[4] + " " + control.get(0)[5] + " " + control.get(0)[6]);
            //CargarMenu();
            if (passdin.equals("1")) {
                new VentanaContrasenia(lblUsuario.getText()).setVisible(true);
            }
            CargarMenu();
            cita.AusentarCitas();

            cita.CitasEnEspera();
            Lista_Diaria = cita.getCitasDelDia();  
            cargarAgendaDiaria();

            tbl.Vizualizar(this, Lista_Diaria);

            hilo.start();  
        }
    }

    public void cargarAgendaDiaria() {
        Lista_Diaria_aux = cita.getCitasDelDia();

        if (Lista_Diaria_aux == null) {
            Lista_Diaria_aux = new ArrayList<>();
        }
        boolean cambio = CompararArraysAgenda();
//        System.out.println("cambio--->"+cambio);
        if (cambio) {
            tbl.Vizualizar(this, Lista_Diaria_aux);
        }
    }

    public void CargarDatosAgenda() {
        try {
            System.out.println("******************CargarDatosAgenda*********************");
            Lista_Diaria = cita.getCitasDelDia();
            Lista_Diaria_Nulo = cita.getDiasNulosDelDia();
            if (Lista_Diaria == null) {
                Lista_Diaria = new ArrayList<>();
            }

            nombreColumnas = new String[]{"Hora", "Paciente", "Estado", "", "", ""};
//        Object[] Columnas = new Object[6];
//        Columnas[0] = "Hora";
//        Columnas[1] = "Paciente";
//        Columnas[2] = "Estado";
//        JLabel Ag = new JLabel();
//        Ag.setToolTipText("Agenda");
//        Ag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/reprogramar16.png")));                 
//        Ag.setPreferredSize(new java.awt.Dimension(16, 16));
//        Columnas[3] = Ag;
//        JLabel hc = new JLabel();
//        hc.setName("v");
//        hc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/repro22.png")));
//        hc.setToolTipText("Historia Clinica");
//        hc.setPreferredSize(new java.awt.Dimension(16, 16));
//        Columnas[4] = hc;
//        JLabel Fact = new JLabel();
//        Fact.setName("v");
//        Fact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/repro22.png")));
//        Fact.setToolTipText("Facturación");
//        Fact.setPreferredSize(new java.awt.Dimension(16, 16));
//        Columnas[5] = Fact;

            if (Lista_Diaria_Nulo == null) {
                Lista_Diaria_Nulo = new ArrayList<>();
            }
            modelo = new DefaultTableModel(nombreColumnas, 0) {
                Class[] types = new Class[]{
                    java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
                };

                public Class getColumnClass(int col) {
                    return types[col];
                }

                public boolean isCellEditable(int row, int col) {
                    //System.out.println("row-->"+row+" -- col-->"+col+"::  ::: "+edit[col]);
                    return false;
                }

            };

            System.out.println("******************************CargarDatosAgenda*****************************" + Lista_Diaria + "----------------" + Lista_Diaria_Nulo);
            String HoraDig = "";
            int i = 0, fil = -1, min = 40, hora = 6;
            int minAu = 20;
            String[] datos;
            Object[] objetos;
            String aux = "";
            while (i < 13) {
                datos = new String[]{"", "", "", "", "", ""};
                objetos = new Object[6];
                if (min == 60) {
                    i++;
                    hora += 1;
                    min = 0;
                }
                JButton btn = new JButton();
                btn.setName("v");
                btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/reprogramar16.png")));
                btn.setToolTipText("Reprogramar");
                btn.setPreferredSize(new java.awt.Dimension(16, 16));
                btn.setContentAreaFilled(false);

                JButton Ag = new JButton();
                Ag.setName("v");
                Ag.setToolTipText("Agenda");
                Ag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/reprogramar16.png")));
                Ag.setPreferredSize(new java.awt.Dimension(16, 16));
                Ag.setContentAreaFilled(false);

                JLabel hc = new JLabel();
                hc.setName("v");
                hc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/repro22.png")));
                hc.setToolTipText("Historia Clinica");
                hc.setPreferredSize(new java.awt.Dimension(16, 16));
                JLabel Fact = new JLabel();
                Fact.setName("v");
                Fact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/repro22.png")));
                Fact.setToolTipText("Facturación");
                Fact.setPreferredSize(new java.awt.Dimension(16, 16));

                HoraDig = (String.valueOf(hora).length() == 1 ? "0" + hora : hora) + ":" + (String.valueOf(min).length() == 1 ? "0" + min : min);
                aux = getHoraNula(HoraDig);
                if (aux.equals("")) {
                    ArrayList<String[]> lista = getDatosxHora(HoraDig);
                    if (lista != null && lista.size() > 0) {
                        for (int j = 0; j < lista.size(); j++) {
                            fil++;                         ///FILA  //PK_CITA, PAUX, ID, PACIENTE, HORA, ESTADO

                            Lista_auxiliar.add(new String[]{"" + fil, "" + lista.get(j)[0], "" + lista.get(j)[1], "" + lista.get(j)[2], "" + lista.get(j)[3]});
                            objetos[0] = "" + getHora(HoraDig);
                            objetos[1] = "" + lista.get(j)[3];
                            objetos[2] = "" + lista.get(j)[5];
                            objetos[3] = btn;
                            objetos[4] = hc;
                            objetos[5] = Fact;
                            modelo.addRow(objetos);
                            //agregarFila(objetos);  
                        }
                    } else {
                        fil++;
                        objetos[0] = getHora(HoraDig);
                        objetos[1] = "";
                        objetos[2] = "";
                        objetos[3] = btn;
                        objetos[4] = hc;
                        objetos[5] = Fact;
                        modelo.addRow(objetos);
                        //agregarFila(objetos);  
                    }

                }
                tblAgendaDiaria.setModel(modelo);
                min += minAu;
            }
            for (i = 0; i < modelo.getColumnCount(); i++) {
                if (i == 0) {
                    tblAgendaDiaria.getColumnModel().getColumn(i).setPreferredWidth(47);
                } else if (i == 1) {
                    tblAgendaDiaria.getColumnModel().getColumn(i).setPreferredWidth(180);
                } else if (i == 2) {
                    tblAgendaDiaria.getColumnModel().getColumn(i).setPreferredWidth(50);
                } else {
                    tblAgendaDiaria.getColumnModel().getColumn(i).setPreferredWidth(20);
                }

                tblAgendaDiaria.getColumnModel().getColumn(i).setResizable(false);
            }
            JTableHeader header = tblAgendaDiaria.getTableHeader();
//        header.setBackground(Color.BLUE);  
//        header.setForeground(Color.red);
            ((DefaultTableCellRenderer) header.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);

            tblAgendaDiaria.setRowHeight(30);
            System.out.println("****************FIN CargarDatosAgenda**********************");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public String getHora(String hora) {
        try {
            String[] dat = hora.split(":");
            int h = Integer.parseInt(dat[0]);
            int b = 0;

            if (h >= 12) {
                b = 1;
                if (h > 12) {
                    h = h - 12;
                }
            }

            return h + ":" + dat[1] + " " + (b == 0 ? "a." : "p.") + " m.";

        } catch (Exception e) {
            System.out.println("ERROR--getHora--" + e.toString());
            return "";
        }
    }

    private void agregarFila(Object[] fila) {
        modelo.addRow(fila);

    }

    public String getHoraNula(String hora) {
        try {
            String ret = "";
            for (int i = 0; i < Lista_Diaria_Nulo.size(); i++) {
                if (Lista_Diaria_Nulo.get(i)[1].equals(hora)) {
                    ret = "NULO";
                    break;
                }
            }
            return ret;
        } catch (Exception e) {
            System.out.println("ERROR --getHoraNula-- " + e.toString());

            return "";
        }
    }

    public ArrayList<String[]> getDatosxHora(String hora) {
        try {

            ArrayList<String[]> lista = new ArrayList<>();
            String hors = "";
            //System.out.println("*************getDatosxHora***" + hora + "******tam--*" + Lista_Diaria.size() + "***");

            for (int i = 0; i < Lista_Diaria.size(); i++) {
                hors = Lista_Diaria.get(i)[4];
                //System.out.println("hors---->" + hors);
                String[] dhors = hors.split(",");
                if (dhors[0].equals(hora)) {
                    lista.add(Lista_Diaria.get(i));
                }
            }
            return lista;
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("ERROR --getDatosxHora-- " + e.toString());
            return null;
        }
    }

    public String[] getDatosxFila(int fila) {
        try {
            String[] ret = null;
            for (String[] dat : Lista_auxiliar) {
                if (dat[0].equals("" + fila)) {
                    ret = dat;
                }
            }
            return ret;
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("ERROR getDatosxFila-->" + e.toString());
            return null;
        }
    }

    public void OcultarMenu() {
        pnlAgenda.setVisible(false);
        pnlPersonas.setVisible(false);
        pnlFacturacion.setVisible(false);

        btnHistoriaClinica.setVisible(false);
        //btnHistoriaClinica.setVisible(false);

        btnHistoriaClinica.setVisible(false);
        btnAgenda.setVisible(false);
        btnFactura.setVisible(false);
        pnlDiasNulos.setVisible(false);
        pnlConfirmacion.setVisible(false);
        pnlPacientes.setVisible(false);
        pnlPacAuxiliar.setVisible(false);
        pnlPersonal.setVisible(false);
        pnlArticulos.setVisible(false);
        pnlConceptos.setVisible(false);
        pnlInformes.setVisible(false);
        //jSeparator1.setVisible(false);
        pnlUsuarios.setVisible(false);
    }

    public void ActualizarMenu() {
        CargarMenu();
    }

    public void CargarMenu() {
        //System.out.println("********************CARGAR MENU************************");
        OcultarMenu();
        //System.out.println("USUARIO----->" + datosUsuario.datos.get(0)[0]);
        List<Map<String, String>> lsta_Menu = general.getMenu(datosUsuario.datos.get(0)[0]);

        if (lsta_Menu.size() == 0) {
            JOptionPane.showMessageDialog(null, "No se le han asignado permisos a los modulos del sistema. Por favor comuniquese con el administrador del sistema.");
            return;
        }

        List<Map<String, String>> lsta_opcG = general.data_list(1, lsta_Menu, new String[]{"IDMOD"}, new String[]{"TPO<->0"});
        List<Map<String, String>> lsta_opcP = general.data_list(1, lsta_Menu, new String[]{"IDMOD"}, new String[]{"TPO<->1"});

        ///////////VERIFICO OPC GRANDES////////////////
        for (Map<String, String> lst : lsta_opcG) {
            if (lst.get("IDMOD").equals("1") && lst.get("V").equals("1")) {
                btnHistoriaClinica.setVisible(true);
            } else if (lst.get("IDMOD").equals("2") && lst.get("V").equals("1")) {
                btnAgenda.setVisible(true);
            } else if (lst.get("IDMOD").equals("3") && lst.get("V").equals("1")) {
                btnFactura.setVisible(true);
            }
        }
        ///////////////VERIFICO OPC GRANDES//////////////////
        List<Map<String, String>> lsta_opcM = general.data_list(1, lsta_opcP, new String[]{"SUB"});
        int a = 0, p = 0, f = 0, b = 0;
        for (Map<String, String> lst : lsta_opcP) {
//            System.out.println("a-->" + a + "____p->" + p + "____f->" + f + "____b->" + b);
//            System.out.println("lst.get(\"IDMOD\")-->" + lst.get("IDMOD"));
//            System.out.println("lst.get(\"V\")-->" + lst.get("V"));

            if (lst.get("IDMOD").equals("11") && lst.get("V").equals("1")) {
                pnlDiasNulos.setVisible(true);
                //jMDiasNulos.setVisible(true);
                if (a == 0) {
                    pnlAgenda.setVisible(true);
                    //jMAgenda.setVisible(true);  
                    a = 1;
                }
//                if(b == 0){
//                    jMBasico.setVisible(true);  
//                    b = 1;
//                }
            } else if (lst.get("IDMOD").equals("12") && lst.get("V").equals("1")) {
                pnlConfirmacion.setVisible(true);
                //jMConfirmacion.setVisible(true);
                if (a == 0) {
                    pnlAgenda.setVisible(true);
                    //jMAgenda.setVisible(true);  
                    a = 1;
                }
//                if(b == 0){
//                    jMBasico.setVisible(true);  
//                    b = 1;
//                }
            } else if (lst.get("IDMOD").equals("21") && lst.get("V").equals("1")) {
                pnlPacientes.setVisible(true);
                //jMPaciente.setVisible(true);
                if (p == 0) {
                    pnlPersonas.setVisible(true);  
                    //jMPersonas.setVisible(true);     
                    p = 1;
                }
//                if(b == 0){
//                    jMBasico.setVisible(true);  
//                    b = 1;   
//                }
            } else if (lst.get("IDMOD").equals("22") && lst.get("V").equals("1")) {
                pnlPacAuxiliar.setVisible(true);
//                jMPacAuxiliar.setVisible(true);
                if (p == 0) {
                    pnlPersonas.setVisible(true);
                    //jMPersonas.setVisible(true);  
                    p = 1;
                }
//                if(b == 0){
//                    jMBasico.setVisible(true);  
//                    b = 1;
//                }
            } else if (lst.get("IDMOD").equals("23") && lst.get("V").equals("1")) {
                pnlPersonal.setVisible(true);
                //jMEmpleados.setVisible(true);
                if (p == 0) {
                    pnlPersonas.setVisible(true);
                    //jMPersonas.setVisible(true);  
                    p = 1;
                }
//                if(b == 0){
//                    jMBasico.setVisible(true);  
//                    b = 1;
//                }
            } else if (lst.get("IDMOD").equals("31") && lst.get("V").equals("1")) {
                pnlArticulos.setVisible(true);
                //jMArticulo.setVisible(true);
                if (f == 0) {
                    pnlFacturacion.setVisible(true);
                    //jMFacturacion.setVisible(true);  
                    f = 1;
                }
//                if(b == 0){
//                    jMBasico.setVisible(true);  
//                    b = 1;
//                }
            } else if (lst.get("IDMOD").equals("32") && lst.get("V").equals("1")) {
                pnlConceptos.setVisible(true);
//                jMConceptos.setVisible(true);
                if (f == 0) {
                    pnlFacturacion.setVisible(true);
                    //jMFacturacion.setVisible(true);  
                    f = 1;
                }
//                if(b == 0){
//                    jMBasico.setVisible(true);  
//                    b = 1;
//                }
            } else if (lst.get("IDMOD").equals("4") && lst.get("V").equals("1")) {
                pnlInformes.setVisible(true);
                //jMInformes.setVisible(true);
            } else if (lst.get("IDMOD").equals("51") && lst.get("V").equals("1")) {
                //jSeparator1.setVisible(true);
                pnlUsuarios.setVisible(true);
//                jMUsuarios.setVisible(true);
//                if(b == 0){
//                    jMBasico.setVisible(true);  
//                    b = 1;
//                }
            }

        }
        //System.out.println("********************END CARGAR MENU************************");
    }

    public void CargarMenuOLD() {
        System.out.println("********************CARGAR MENU************************");
        OcultarMenu();
        System.out.println("USUARIO----->" + datosUsuario.datos.get(0)[0]);
        List<Map<String, String>> lsta_Menu = general.getMenu(datosUsuario.datos.get(0)[0]);

        if (lsta_Menu.size() == 0) {
            JOptionPane.showMessageDialog(null, "No se le han asignado permisos a los modulos del sistema. Por favor comuniquese con el administrador del sistema.");
            return;
        }

        List<Map<String, String>> lsta_opcG = general.data_list(1, lsta_Menu, new String[]{"IDMOD"}, new String[]{"TPO<->0"});
        List<Map<String, String>> lsta_opcP = general.data_list(1, lsta_Menu, new String[]{"IDMOD"}, new String[]{"TPO<->1"});

        ///////////VERIFICO OPC GRANDES////////////////
        for (Map<String, String> lst : lsta_opcG) {
            if (lst.get("IDMOD").equals("1")) {
                btnHistoriaClinica.setVisible(true);
            } else if (lst.get("IDMOD").equals("2")) {
                btnAgenda.setVisible(true);
            } else if (lst.get("IDMOD").equals("3")) {
                btnFactura.setVisible(true);
            }
        }
        ///////////////VERIFICO OPC GRANDES//////////////////
        List<Map<String, String>> lsta_opcM = general.data_list(1, lsta_opcP, new String[]{"SUB"});
        int a = 0, p = 0, f = 0, b = 0;
        for (Map<String, String> lst : lsta_opcP) {
            System.out.println("a-->" + a + "____p->" + p + "____f->" + f + "____b->" + b);
            System.out.println("lst.get(\"IDMOD\")-->" + lst.get("IDMOD"));

            if (lst.get("IDMOD").equals("11")) {
                jMDiasNulos.setVisible(true);
                if (a == 0) {
                    jMAgenda.setVisible(true);
                    a = 1;
                }
                if (b == 0) {
                    jMBasico.setVisible(true);
                    b = 1;
                }
            } else if (lst.get("IDMOD").equals("12")) {
                jMConfirmacion.setVisible(true);
                if (a == 0) {
                    jMAgenda.setVisible(true);
                    a = 1;
                }
                if (b == 0) {
                    jMBasico.setVisible(true);
                    b = 1;
                }
            } else if (lst.get("IDMOD").equals("21")) {
                jMPaciente.setVisible(true);
                if (p == 0) {
                    jMPersonas.setVisible(true);
                    p = 1;
                }
                if (b == 0) {
                    jMBasico.setVisible(true);
                    b = 1;
                }
            } else if (lst.get("IDMOD").equals("22")) {
                jMPacAuxiliar.setVisible(true);
                if (p == 0) {
                    jMPersonas.setVisible(true);
                    p = 1;
                }
                if (b == 0) {
                    jMBasico.setVisible(true);
                    b = 1;
                }
            } else if (lst.get("IDMOD").equals("23")) {
                jMEmpleados.setVisible(true);
                if (p == 0) {
                    jMPersonas.setVisible(true);
                    p = 1;
                }
                if (b == 0) {
                    jMBasico.setVisible(true);
                    b = 1;
                }
            } else if (lst.get("IDMOD").equals("31")) {
                jMArticulo.setVisible(true);
                if (f == 0) {
                    jMFacturacion.setVisible(true);
                    f = 1;
                }
                if (b == 0) {
                    jMBasico.setVisible(true);
                    b = 1;
                }
            } else if (lst.get("IDMOD").equals("32")) {
                jMConceptos.setVisible(true);
                if (f == 0) {
                    jMFacturacion.setVisible(true);
                    f = 1;
                }
                if (b == 0) {
                    jMBasico.setVisible(true);
                    b = 1;
                }
            } else if (lst.get("IDMOD").equals("4")) {
                jMInformes.setVisible(true);
            } else if (lst.get("IDMOD").equals("51")) {
                jSeparator1.setVisible(true);
                jMUsuarios.setVisible(true);
                if (b == 0) {
                    jMBasico.setVisible(true);
                    b = 1;
                }
            }

        }
        System.out.println("********************END CARGAR MENU************************");
    }

    public void OcultarMnConfig(boolean b) {
        pnlConfig.setVisible(b);
    }

    private boolean CompararArraysAgenda() {
        try {
            boolean ret = false;

            if (Lista_Diaria_aux.size() > Lista_Diaria.size()) {
                Lista_Diaria = cita.getCitasDelDia();
                ret = true;
            }else if(Lista_Diaria_aux.size() < Lista_Diaria.size()){
                Lista_Diaria = cita.getCitasDelDia();
                ret = true;
            } else {
                for (int i = 0; i < Lista_Diaria.size(); i++) {//             

                    if ((Lista_Diaria.get(i)[9].equals("0") && Lista_Diaria_aux.get(i)[8].equals("3"))) {
                        Lista_Diaria.get(i)[9] = "1";
                        Lista_Diaria.get(i)[5] = Lista_Diaria_aux.get(i)[5];
                        ret = true;
                        break;
                        //Lista_Diaria.set(i, nombreColumnas)
                    } else if ((Lista_Diaria.get(i)[1].equals("2") && !Lista_Diaria.get(i)[13].equals("O") && (Lista_Diaria_aux.get(i)[10].equals("1") || Lista_Diaria_aux.get(i)[11].equals("1")))) {
                        Lista_Diaria.get(i)[1] = Lista_Diaria_aux.get(i)[1];
                        Lista_Diaria.get(i)[2] = Lista_Diaria_aux.get(i)[2];
                        ret = true;
                        break;
                    } else if (Lista_Diaria.get(i)[8].equals("0") && Lista_Diaria_aux.get(i)[8].equals("1")) {
                        Lista_Diaria.get(i)[8] = "1";
                        Lista_Diaria.get(i)[5] = Lista_Diaria_aux.get(i)[5];
                        ret = true;
                        break;
                    }
                }
            }

            return ret;

        } catch (Exception e) {
            return false;
        }
    }

    private void cerrarSesion() {
        new ventanainiciarsesion().setVisible(true);
        this.dispose();
    }

}
