/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Busquedas.ventanaBusquedapacienteinf;
import Informes.Descripcioninformespdf;
import Utilidades.Utilidades;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.SwingConstants;

/**
 *
 * @author Acer
 */
public class VentanaInformes1 extends javax.swing.JFrame {
    public ArrayList<int[]> listaPosiciones;
    public ArrayList<String[]> listacategorias = new ArrayList<>();
    public ArrayList<String[]> listainformes = new ArrayList<>();
    public DefaultListModel modlistCategorias;
    public DefaultListModel modlistInformes;
    public Calendar cale;
    public SimpleDateFormat sdf;
    public Descripcioninformespdf informe;
    
    public javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
    
    public javax.swing.JLabel lblPaciente = new javax.swing.JLabel();
    public javax.swing.JTextField txtPaciente = new javax.swing.JTextField();
    public javax.swing.JButton btnBuscarP = new javax.swing.JButton();
    public javax.swing.JLabel lblIdPaciente = new javax.swing.JLabel();
    public javax.swing.JComboBox cbBandera = new javax.swing.JComboBox();
    public javax.swing.JLabel lblBandera = new javax.swing.JLabel(); 
    public javax.swing.JRadioButton rbInfohistorico = new javax.swing.JRadioButton();
    public com.toedter.calendar.JDateChooser jdFechafinal = new com.toedter.calendar.JDateChooser();
    public com.toedter.calendar.JDateChooser jdFechainicial = new com.toedter.calendar.JDateChooser();
    public javax.swing.JLabel lblFechafinal = new javax.swing.JLabel();
    public javax.swing.JLabel lblFechainicial = new javax.swing.JLabel();
    
    public javax.swing.JCheckBox chPanoramica = new javax.swing.JCheckBox();
    public javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
    public javax.swing.JCheckBox chPanoramicaTodas = new javax.swing.JCheckBox();
    public javax.swing.JCheckBox chRadiografia = new javax.swing.JCheckBox();
    public javax.swing.JCheckBox chRadiografiaTodas = new javax.swing.JCheckBox();
    public javax.swing.JCheckBox chOdontogramaTodas = new javax.swing.JCheckBox();
    public javax.swing.JCheckBox chOdontograma = new javax.swing.JCheckBox();   
    public javax.swing.JCheckBox chFotografiaTodas = new javax.swing.JCheckBox();
    public javax.swing.JCheckBox chFotografia = new javax.swing.JCheckBox();
    private int x, y;
    /**
     * Creates new form VentanaInformes
     */
    public VentanaInformes1() {
        initComponents();
        Utilidades.EstablecerIcono(this);
        cargarArray();
        sdf = new SimpleDateFormat("yyyy-MM-dd");
        cale=Calendar.getInstance();  
        listaPosiciones = new ArrayList<>();
        modlistCategorias = new DefaultListModel();  
        modlistInformes = new DefaultListModel();
        informe = new Descripcioninformespdf();
        this.setLocationRelativeTo(null);
        llenarCategorias();
    }
         
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCategoria = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listInformes = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        PanelOpciones = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnGenerar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generar Informes");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 82, 118)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(21, 67, 96))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(26, 82, 118));
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        listCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listCategoria.setForeground(new java.awt.Color(21, 67, 96));
        listCategoria.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Citas", "Historia Clinica", "Paciente", "Facturas" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listCategoria.setSelectionBackground(new java.awt.Color(21, 67, 96));
        listCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listCategoriaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(listCategoria);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(21, 67, 96))); // NOI18N

        listInformes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listInformes.setForeground(new java.awt.Color(21, 67, 96));
        listInformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listInformesMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(listInformes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 20, 380));

        PanelOpciones.setBackground(new java.awt.Color(255, 255, 255));
        PanelOpciones.setForeground(new java.awt.Color(21, 67, 96));
        PanelOpciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(21, 67, 96));
        jLabel3.setText("Opciones");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(21, 67, 96));
        jLabel8.setText("Fecha Inicio");

        jDateChooser1.setForeground(new java.awt.Color(21, 67, 96));

        jDateChooser2.setForeground(new java.awt.Color(21, 67, 96));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(21, 67, 96));
        jLabel9.setText("Fecha Fin");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(21, 67, 96));
        jLabel7.setText("Filtro");

        jCheckBox1.setText("Ausentes");

        jCheckBox2.setText("Cancelados");

        jCheckBox3.setText("Atendidos");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelOpcionesLayout = new javax.swing.GroupLayout(PanelOpciones);
        PanelOpciones.setLayout(PanelOpcionesLayout);
        PanelOpcionesLayout.setHorizontalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(jLabel3))
                            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addGap(48, 48, 48)
                                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jCheckBox2))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelOpcionesLayout.setVerticalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOpcionesLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jCheckBox1))
                .addGap(15, 15, 15)
                .addComponent(jCheckBox2)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jPanel1.add(PanelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 430, 380));

        jPanel4.setBackground(new java.awt.Color(26, 82, 118));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/minimizar.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/cerrar_1.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 30, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gestionar Informes");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, 152, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 30));

        jPanel5.setBackground(new java.awt.Color(26, 82, 118));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("Generar");
        btnGenerar.setBorderPainted(false);
        btnGenerar.setContentAreaFilled(false);
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        jPanel5.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCategoriaMousePressed
        SeleccionarCategoria();
    }//GEN-LAST:event_listCategoriaMousePressed

    private void listInformesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listInformesMousePressed
        MostrarOpciones();  
    }//GEN-LAST:event_listInformesMousePressed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        GenerarN();
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setState(VentanaInformes1.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        this.setLocation(this.getLocation().x + evt.getX()-x, this.getLocation().y + evt.getY()-y);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    public void GenerarN(){
        int cat = listCategoria.getSelectedIndex();
        int inf = listInformes.getSelectedIndex();
        Map<String, String> list = new HashMap <String, String>();
        list.put("cat", ""+cat);
        list.put("inf", ""+inf);
        if(cat == 0){
            if(inf == 0){//Diario
                list.put("fini", ""+sdf.format(jdFechainicial.getCalendar().getTime()));
            }else if(inf == 1){//Historico Citas
                list.put("idpac", ""+lblIdPaciente.getText());
            }else if(inf == 2){//Demanda Inducida
                list.put("fini",""+sdf.format(jdFechainicial.getCalendar().getTime()));
            }        
        }else if(cat == 1){
            if(inf == 0){//Imprimir Historia Clinica
                list.put("idpac", ""+lblIdPaciente.getText());
                list.put("chP", ""+(chPanoramica.isSelected()?"1":"0"));
                list.put("chPT", ""+(chPanoramicaTodas.isSelected()?"1":"0"));
                list.put("chR", ""+(chRadiografia.isSelected()?"1":"0"));
                list.put("chRT", ""+(chRadiografiaTodas.isSelected()?"1":"0"));
                list.put("chO", ""+(chOdontograma.isSelected()?"1":"0"));
                list.put("chOT", ""+(chOdontogramaTodas.isSelected()?"1":"0"));
                list.put("chF", ""+(chFotografia.isSelected()?"1":"0"));
                list.put("chFT", ""+(chFotografiaTodas.isSelected()?"1":"0"));
            }else if(inf == 1){//Historias Cerradas
                String fini = "";
                String ffin ="";
                if(jdFechainicial.getCalendar() != null){
                    fini = ""+sdf.format(jdFechainicial.getCalendar().getTime());
                }
                System.out.println("fini-.-"+ fini+"///");
                list.put("fini", ""+fini);
                  if(jdFechafinal.getCalendar() != null){
                    ffin = ""+sdf.format(jdFechafinal.getCalendar().getTime());
                }
                System.out.println("ffin-.-"+ ffin+"///");
                list.put("ffin", ""+ffin);
                list.put("rHist",""+rbInfohistorico.isSelected());
            }
//            }else if(inf == 2){//Historias Inactivas
//                String fini = "";
//                String ffin ="";
//                if(jdFechainicial.getCalendar() != null){
//                    fini = ""+sdf.format(jdFechainicial.getCalendar().getTime());
//                }
//                System.out.println("fini-.-"+ fini+"///");
//                list.put("fini", ""+fini);
//                  if(jdFechafinal.getCalendar() != null){
//                    ffin = ""+sdf.format(jdFechafinal.getCalendar().getTime());
//                }
//                System.out.println("ffin-.-"+ ffin+"///");
//                list.put("ffin", ""+ffin);
//                list.put("rHist",""+rbInfohistorico.isSelected());
//            }
        }else if(cat == 2){
            if(inf == 0){//Estados
                list.put("tipo", ""+cbBandera.getSelectedItem());
                System.out.println("valor bandera"+cbBandera.getSelectedItem());
                String fini = "";
                String ffin ="";
                if(jdFechainicial.getCalendar() != null){
                    fini = ""+sdf.format(jdFechainicial.getCalendar().getTime());
                }
                System.out.println("fini-.-"+ fini+"///");
                list.put("fini", ""+fini);
                  if(jdFechafinal.getCalendar() != null){
                    ffin = ""+sdf.format(jdFechafinal.getCalendar().getTime());
                }
                System.out.println("ffin-.-"+ ffin+"///");
                list.put("ffin", ""+ffin);
                list.put("rHist",""+rbInfohistorico.isSelected());
            }else if(inf == 1){//Facturas por Mes
                String fini = "";
                String ffin ="";
                if(jdFechainicial.getCalendar() != null){
                    fini = ""+sdf.format(jdFechainicial.getCalendar().getTime());
                }
                System.out.println("fini-.-"+ fini+"///");
                list.put("fini", ""+fini);
                  if(jdFechafinal.getCalendar() != null){
                    ffin = ""+sdf.format(jdFechafinal.getCalendar().getTime());
                }
                System.out.println("ffin-.-"+ ffin+"///");
                list.put("ffin", ""+ffin);
                list.put("rHist",""+rbInfohistorico.isSelected());
            }else if(inf == 2){//Recaudo por Dia
                list.put("fini", ""+sdf.format(jdFechainicial.getCalendar().getTime()));
            }else if(inf == 3){//Recaudo por Mes
                String fini = "";
                String ffin ="";
                if(jdFechainicial.getCalendar() != null){
                    fini = ""+sdf.format(jdFechainicial.getCalendar().getTime());
                }
                System.out.println("fini-.-"+ fini+"///");
                list.put("fini", ""+fini);
                  if(jdFechafinal.getCalendar() != null){
                    ffin = ""+sdf.format(jdFechafinal.getCalendar().getTime());
                }
                System.out.println("ffin-.-"+ ffin+"///");
                list.put("ffin", ""+ffin);
                list.put("rHist",""+rbInfohistorico.isSelected());
            }else if(inf == 4){//Recaudo Tipo Pago
                list.put("tipo", ""+cbBandera.getSelectedItem());
                String fini = "";
                String ffin ="";
                if(jdFechainicial.getCalendar() != null){
                    fini = ""+sdf.format(jdFechainicial.getCalendar().getTime());
                }
                System.out.println("fini-.-"+ fini+"///");
                list.put("fini", ""+fini);
                  if(jdFechafinal.getCalendar() != null){
                    ffin = ""+sdf.format(jdFechafinal.getCalendar().getTime());
                }
                System.out.println("ffin-.-"+ ffin+"///");
                list.put("ffin", ""+ffin);
                list.put("rHist",""+rbInfohistorico.isSelected());
            }else if(inf == 5){//Abono por Pacientes
                list.put("idpac", ""+lblIdPaciente.getText());
            }
        }else if(cat == 3){
            if(inf == 0){//Pacientes Auxiliares
                list.put("tipo", ""+cbBandera.getSelectedItem());
            }else if(inf == 1){//Pacientes Activos
                list.put("fini", ""+sdf.format(jdFechainicial.getCalendar().getTime()));
            }
//            else if(inf == 2){//Pacientes Terminados
//                list.put("fini", ""+sdf.format(jdFechainicial.getCalendar().getTime()));
//                list.put("ffin", ""+sdf.format(jdFechafinal.getCalendar().getTime()));
//                list.put("rHist",""+rbInfohistorico.isSelected());
//            }
            else if(inf == 3){//Pacientes por Terminar
                list.put("fini", ""+sdf.format(jdFechainicial.getCalendar().getTime()));
                list.put("ffin", ""+sdf.format(jdFechafinal.getCalendar().getTime()));
                //list.put("rHist",""+rbInfohistorico.isSelected());  
            }
        }
        
        String archivo = informe.Generarinformes(list); 
        
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInformes1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInformes1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInformes1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInformes1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInformes1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList listCategoria;
    private javax.swing.JList listInformes;
    // End of variables declaration//GEN-END:variables

    

    private void cargarArray() {
        /////////////////////////// CAT, NOM
        listacategorias.add(new String[]{"0","Citas"});
        listacategorias.add(new String[]{"1","Historia Clinica"});
        listacategorias.add(new String[]{"2","Factura"});
        listacategorias.add(new String[]{"3","Paciente"});
        /////////////7////////////CAT, ID, NOm    
        listainformes.add(new String[]{"0","0","Diario"});
        listainformes.add(new String[]{"0","1","Historico Citas"});
        listainformes.add(new String[]{"0","2","Demanda Inducida"});
        listainformes.add(new String[]{"1","0","Imprimir Historia Clinica"});
        listainformes.add(new String[]{"1","1","Historias Cerradas"});
        //listainformes.add(new String[]{"1","2","Historias Inactivas"});
        listainformes.add(new String[]{"2","0","Estados"});
        listainformes.add(new String[]{"2","1","Facturas por Mes"});
        listainformes.add(new String[]{"2","2","Recaudo por Dia"});
        listainformes.add(new String[]{"2","3","Recaudo por Mes"});
        listainformes.add(new String[]{"2","4","Recaudo Tipo Pago"});
        listainformes.add(new String[]{"2","5","Abono por Pacientes"});
        listainformes.add(new String[]{"3","0","Pacientes Auxiliares"});
        listainformes.add(new String[]{"3","1","Pacientes Activos"});
       //listainformes.add(new String[]{"3","2","Pacientes Terminados"});
        listainformes.add(new String[]{"3","2","Pacientes por Terminar"});
    }

    private void llenarCategorias() {
        //cbCate.addItem("Seleccionar");
        for(int i = 0; i < listacategorias.size(); i++){
            modlistCategorias.addElement(listacategorias.get(i)[1]);                
        }
        listCategoria.setModel(modlistCategorias);
    }
    
    private void llenarInforme(String idcat) {
        LimpiarPanelOpciones();
        modlistInformes.removeAllElements();
        listInformes.setModel(modlistInformes);
        for(String[] lst:listainformes){
            if(lst[0].equals(idcat)){
                modlistInformes.addElement(lst[2]);           
            }
        }
        listInformes.setModel(modlistInformes);
    }
    
    private void SeleccionarCategoria() {
        int ind = listCategoria.getSelectedIndex();
        System.out.println("ind----->"+ind);
        //ind = getCategoria(modlistCategorias.getElementAt());
        llenarInforme(""+ind);
    }
    
    private String getCategoria(String cat) {
        String retorno ="";
        for(int i =0; i<listacategorias.size(); i++){
            if (listacategorias.get(i)[1].equals(cat)){
                retorno=listacategorias.get(i)[0];
                break;
            }
        }
        return retorno;
    }
    
    public void BuscarPaciente(){
        //new ventanaBusquedapacienteinf(this).setVisible(true);
        //new ventanaBusquedapacienteinf(this).setVisible(true);
        //JOptionPane.showMessageDialog(null, "HELOOOOOOOOO O O O O O O ");
    }

    private void LimpiarPanelOpciones() {
        PanelOpciones.removeAll();
        PanelOpciones.repaint();
        
        lblPaciente = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        btnBuscarP = new javax.swing.JButton();
        lblIdPaciente = new javax.swing.JLabel();
        cbBandera = new javax.swing.JComboBox();
        lblBandera = new javax.swing.JLabel();        
        rbInfohistorico = new javax.swing.JRadioButton();
        jdFechafinal = new com.toedter.calendar.JDateChooser();
        jdFechainicial = new com.toedter.calendar.JDateChooser();
        lblFechafinal = new javax.swing.JLabel();
        lblFechainicial = new javax.swing.JLabel();
        
        chPanoramica = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        chPanoramicaTodas = new javax.swing.JCheckBox();
        chRadiografia = new javax.swing.JCheckBox();
        chRadiografiaTodas = new javax.swing.JCheckBox();
        chOdontogramaTodas = new javax.swing.JCheckBox();
        chOdontograma = new javax.swing.JCheckBox();
        chFotografiaTodas = new javax.swing.JCheckBox();
        chFotografia = new javax.swing.JCheckBox();
        
        
    }
    
    private void MostrarOpciones() {
        LimpiarPanelOpciones();
        
        int indC = listCategoria.getSelectedIndex();
        int indI = listInformes.getSelectedIndex();
        
        if(indC == 0){//CITAS
            if(indI == 0){//Diario
                MostrarOpcDiario();                
            }else if(indI == 1){//Historico Citas
                MostrarOpcHistCitas();                
            }else if(indI == 2){//Demanda Inducida
                MostrarOpcDiario();
            }
        }else if(indC == 1){////Historia Clinica
            if (indI == 0){ //imprimir historia clinica
                MostrarOpcHistClinica();  
            }else if (indI == 1){//Historias cerradas  
                MostrarOpcHistCerradas();
            }
//            else if (indI == 2){//Historias inactivas
//                MostrarOpcHistCerradas();
//            }
        }else if(indC == 2){////Factura
            if (indI == 0){ //Estados
                MostrarOpcEstados();
            }else if (indI == 1){//Facturas por Mes
                MostrarOpcHistCerradas();
            }else if (indI == 2){//Recaudo por Dia
               MostrarOpcDiario();  
            }else if (indI == 3){//Recaudo por Mes
                MostrarOpcHistCerradas();
            }else if (indI == 4){//Recaudo Tipo Pago
                MostrarOpcTpoPago();
            }else if (indI == 5){//Abono por Pacientes
                MostrarOpcHistCitas();                
            }
        }else if(indC == 3){////Paciente
           if (indI == 0){ //Pacientes Auxiliares
                MostrarOpcPacAux();
           }if(indI == 1){//Pacientes Activos
                MostrarOpcDiario(); 
            }
//           else if (indI == 2){//Pacientes Terminados  
//                MostrarOpcHistCerradas();  
//            }
           else if (indI == 2){//Pacientes por Terminar 
                MostrarOpcPacxTerminar();
            }
        }  
        
    }

    private void MostrarOpcDiario(){  
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 67, 96));
        jLabel1.setText("Opciones");
        
        lblFechainicial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFechainicial.setForeground(new java.awt.Color(21, 67, 96));
        lblFechainicial.setText("Fecha: ");
        jdFechainicial.setDateFormatString("dd/MM/yyyy");
        
                
        javax.swing.GroupLayout PanelOpcionesLayout = new javax.swing.GroupLayout(PanelOpciones);
        PanelOpciones.setLayout(PanelOpcionesLayout);
        PanelOpcionesLayout.setHorizontalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechainicial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        PanelOpcionesLayout.setVerticalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        
        
        
    }

    private void MostrarOpcHistCitas() {
        
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 67, 96));
        jLabel1.setText("Opciones");
        
        btnBuscarP.setText("Buscar");
        btnBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPaciente();
            }
        });
        
        lblPaciente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPaciente.setForeground(new java.awt.Color(21, 67, 96));
        lblPaciente.setText("Paciente:");
        lblIdPaciente.setText("");
        lblIdPaciente.setVisible(false);
        
        txtPaciente.setBorder(null);
        txtPaciente.setText("");
        txtPaciente.setEnabled(false);
        
        javax.swing.GroupLayout PanelOpcionesLayout = new javax.swing.GroupLayout(PanelOpciones);
        PanelOpciones.setLayout(PanelOpcionesLayout);
        PanelOpcionesLayout.setHorizontalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)            
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOpcionesLayout.createSequentialGroup()
                //.addContainerGap()
                .addGap(180, 180, 180)
                .addComponent(jLabel1)
                .addGap(183, 183, 183))
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addComponent(lblPaciente) 
                        .addGap(18, 18, 18)
                        .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnBuscarP)
                        .addGap(4, 4, 4)
                        .addComponent(lblIdPaciente))))
        );
        PanelOpcionesLayout.setVerticalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnBuscarP))
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblIdPaciente)))
                .addGap(18, 18, 18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }

    private void MostrarOpcHistCerradas() {
        System.out.println("");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 67, 96));
        jLabel1.setText("Opciones");
        
        jdFechafinal.setDateFormatString("dd/MM/yyyy");
  
        jdFechainicial.setDateFormatString("dd/MM/yyyy");
        rbInfohistorico.setText("Informe Historico");
        rbInfohistorico.setHorizontalTextPosition(SwingConstants.LEFT);
        lblFechafinal.setText("Fecha Fin:"); 

        lblFechainicial.setText("Fecha Inicio:");


        javax.swing.GroupLayout PanelOpcionesLayout = new javax.swing.GroupLayout(PanelOpciones);
        PanelOpciones.setLayout(PanelOpcionesLayout);
        PanelOpcionesLayout.setHorizontalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbInfohistorico)
                            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                                .addComponent(lblFechainicial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lblFechafinal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jdFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        PanelOpcionesLayout.setVerticalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(rbInfohistorico))
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addComponent(jdFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
    }

    private void MostrarOpcPacxTerminar() {
        System.out.println("*************************MostrarOpcPacxTerminar");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 67, 96));
        jLabel1.setText("Opciones");
        
        jdFechafinal.setDateFormatString("dd/MM/yyyy");
  
        jdFechainicial.setDateFormatString("dd/MM/yyyy");
        //rbInfohistorico.setText("Informe Historico");
        //rbInfohistorico.setHorizontalTextPosition(SwingConstants.LEFT);
        lblFechafinal.setText("Fecha Fin:"); 

        lblFechainicial.setText("Fecha Inicio:");


        javax.swing.GroupLayout PanelOpcionesLayout = new javax.swing.GroupLayout(PanelOpciones);
        PanelOpciones.setLayout(PanelOpcionesLayout);
        PanelOpcionesLayout.setHorizontalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            //.addComponent(rbInfohistorico)
                            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                                .addComponent(lblFechainicial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lblFechafinal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jdFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        PanelOpcionesLayout.setVerticalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        //.addComponent(rbInfohistorico)
                    )
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addComponent(jdFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
    }
    
    private void MostrarOpcEstados() {
        
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 67, 96));
        jLabel1.setText("Opciones");
        
        lblBandera.setText("Estado:");
        
        cbBandera.removeAllItems();
        cbBandera.addItem("Seleccionar");  
        cbBandera.addItem("Todos");
        cbBandera.addItem("Anulada");
        cbBandera.addItem("Pagado");
        cbBandera.addItem("Vigente");
        
        rbInfohistorico.setText("Historico");
        rbInfohistorico.setBackground(Color.WHITE);
        rbInfohistorico.setHorizontalTextPosition(SwingConstants.LEFT);
        jdFechafinal.setDateFormatString("dd/MM/yyyy");

        jdFechainicial.setDateFormatString("dd/MM/yyyy");

        lblFechafinal.setText("Fecha Fin:");
        lblFechainicial.setText("Fecha Inicio:");

        javax.swing.GroupLayout PanelOpcionesLayout = new javax.swing.GroupLayout(PanelOpciones);
        PanelOpciones.setLayout(PanelOpcionesLayout);
        PanelOpcionesLayout.setHorizontalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1))
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblBandera)
                        .addGap(26, 26, 26)
                        .addComponent(cbBandera, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbInfohistorico)
                            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGap(180, 180, 180)
                                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                                        .addComponent(lblFechainicial)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jdFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(lblFechafinal)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jdFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        PanelOpcionesLayout.setVerticalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblBandera))
                    .addComponent(cbBandera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(rbInfohistorico))
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addComponent(jdFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }

    private void MostrarOpcTpoPago() {
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 67, 96));
        jLabel1.setText("Opciones");
        
        lblBandera.setText("Tipo Pago:");
        
        cbBandera.removeAllItems();
        cbBandera.addItem("Seleccionar");  
        cbBandera.addItem("Todos");
        cbBandera.addItem("Efectivo");
        cbBandera.addItem("Tarjeta");
        
        rbInfohistorico.setText("Informe Historico");
        rbInfohistorico.setHorizontalTextPosition(SwingConstants.LEFT);
        jdFechafinal.setDateFormatString("dd/MM/yyyy");

        jdFechainicial.setDateFormatString("dd/MM/yyyy");

        lblFechafinal.setText("Fecha Fin:");
        lblFechainicial.setText("Fecha Inicio:"); 

        javax.swing.GroupLayout PanelOpcionesLayout = new javax.swing.GroupLayout(PanelOpciones);
        PanelOpciones.setLayout(PanelOpcionesLayout);
        PanelOpcionesLayout.setHorizontalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblBandera)
                        .addGap(26, 26, 26)
                        .addComponent(cbBandera, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbInfohistorico)
                            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                                        .addComponent(lblFechainicial)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jdFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(lblFechafinal)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jdFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        PanelOpcionesLayout.setVerticalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblBandera))
                    .addComponent(cbBandera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(rbInfohistorico))
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addComponent(jdFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }

    private void MostrarOpcPacAux() {
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 67, 96));
        jLabel1.setText("Opciones");
        
        lblBandera.setText("Tipo Pago:");
        
        cbBandera.removeAllItems();
        cbBandera.addItem("Seleccionar");  
        cbBandera.addItem("Todos");  
        cbBandera.addItem("Activo");  
        cbBandera.addItem("Inactivo");
        
        javax.swing.GroupLayout PanelOpcionesLayout = new javax.swing.GroupLayout(PanelOpciones);
        PanelOpciones.setLayout(PanelOpcionesLayout);
        PanelOpcionesLayout.setHorizontalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGap(180, 180, 180)
                .addComponent(jLabel1))
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addComponent(lblBandera)
                        .addGap(26, 26, 26)
                        .addComponent(cbBandera, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        PanelOpcionesLayout.setVerticalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblBandera))
                    .addComponent(cbBandera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
    }
    
    
    private void MostrarOpcHistClinica() {
        try{
            System.out.println("MostrarOpcHistClinica-----");
            jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(21, 67, 96));
            jLabel1.setText("Opciones");

            btnBuscarP.setText("Buscar");
            btnBuscarP.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BuscarPaciente();
                }
            });

            lblPaciente.setText("Paciente:");
            lblIdPaciente.setText("");
            lblIdPaciente.setVisible(false);
            txtPaciente.setText("");
            txtPaciente.setEnabled(false);

            chPanoramica.setBackground(new java.awt.Color(255, 255, 255));
            chPanoramica.setText("Panoramicas");

            jLabel2.setText("Imagenes");

            chPanoramicaTodas.setBackground(new java.awt.Color(255, 255, 255));
            chPanoramicaTodas.setText("Todas");

            chRadiografia.setBackground(new java.awt.Color(255, 255, 255));
            chRadiografia.setText("Radiografias");

            chRadiografiaTodas.setBackground(new java.awt.Color(255, 255, 255));
            chRadiografiaTodas.setText("Todas");

            chOdontogramaTodas.setBackground(new java.awt.Color(255, 255, 255));
            chOdontogramaTodas.setText("Todas");
            chOdontograma.setSelected(true);

            chOdontograma.setBackground(new java.awt.Color(255, 255, 255));
            chOdontograma.setText("Odontograma");
            

            chFotografiaTodas.setBackground(new java.awt.Color(255, 255, 255));
            chFotografiaTodas.setText("Todas");

            chFotografia.setBackground(new java.awt.Color(255, 255, 255));
            chFotografia.setText("Fotografias");
            
            chPanoramica.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    EstadoCheck(0);
                }
            });
            chRadiografia.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    EstadoCheck(1);
                }
            });
            chOdontograma.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    EstadoCheck(2);
                }
            });
            chFotografia.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    EstadoCheck(3);
                }
            });
            
            chOdontograma.setEnabled(false);
            chPanoramicaTodas.setEnabled(false);            
            chRadiografiaTodas.setEnabled(false);
            chOdontogramaTodas.setEnabled(true);
            chFotografiaTodas.setEnabled(false);

            javax.swing.GroupLayout PanelOpcionesLayout = new javax.swing.GroupLayout(PanelOpciones);
            
            ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            PanelOpciones.setLayout(PanelOpcionesLayout);
            PanelOpcionesLayout.setHorizontalGroup(
                PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelOpcionesLayout.createSequentialGroup()
                    .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelOpcionesLayout.createSequentialGroup()
                            .addGap(26, 26, 26)  
                            .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(lblPaciente))
                            .addGap(18, 18, 18)
                            .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                                        .addComponent(chFotografia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chFotografiaTodas))
                                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                                        .addComponent(chPanoramica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chPanoramicaTodas))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOpcionesLayout.createSequentialGroup()
                                        .addComponent(chRadiografia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chRadiografiaTodas))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOpcionesLayout.createSequentialGroup()
                                        .addComponent(chOdontograma)
                                        .addGap(18, 18, 18)
                                        .addComponent(chOdontogramaTodas)))
                                .addGroup(PanelOpcionesLayout.createSequentialGroup()
                                    .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBuscarP)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblIdPaciente))))
                        .addGroup(PanelOpcionesLayout.createSequentialGroup()
                            .addGap(184, 184, 184)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(25, Short.MAX_VALUE))
            );
            PanelOpcionesLayout.setVerticalGroup(
                PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelOpcionesLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabel1)
                    .addGap(20, 20, 20)
                    .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPaciente)
                        .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarP)
                        .addComponent(lblIdPaciente))
                    .addGap(18, 18, 18)
                    .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chPanoramica)
                        .addComponent(jLabel2)
                        .addComponent(chPanoramicaTodas))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chRadiografia)
                        .addComponent(chRadiografiaTodas))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chOdontograma)
                        .addComponent(chOdontogramaTodas))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chFotografia)
                        .addComponent(chFotografiaTodas))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    public void EstadoCheck(int opc) {
        boolean val = false;
        if(opc == 0){//Panoramica
            if(chPanoramica.isSelected()){//true
                chPanoramicaTodas.setEnabled(true);
            }else{
                chPanoramicaTodas.setEnabled(false);
                chPanoramicaTodas.setSelected(false);
            }
            
        }else if(opc == 1){//RAdiografia
            if(chRadiografia.isSelected()){//true
                chRadiografiaTodas.setEnabled(true);
            }else{
                chRadiografiaTodas.setEnabled(false);
                chRadiografiaTodas.setSelected(false);
            }
        }else if(opc == 2){//Odontograma
            if(chOdontograma.isSelected()){//true
                chOdontogramaTodas.setEnabled(true);
            }else{
                chOdontogramaTodas.setEnabled(false);
                chOdontogramaTodas.setSelected(false);
            }
        }else if(opc == 3){//Fotografia
            if(chFotografia.isSelected()){//true
                chFotografiaTodas.setEnabled(true);
            }else{
                chFotografiaTodas.setEnabled(false);
                chFotografiaTodas.setSelected(false);
            }
        }
    }
    
    
}

