/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import BaseDeDatos.gestorMySQL;
import Busquedas.ventanaBusqueda;
import Busquedas.ventanaBusquedaPerfil;
import Busquedas.ventanaBusquedaUsuario;
import Control.ControlUsuarios;
import Tabla.TablaPermisos;
import Utilidades.Utilidades;
import Utilidades.datosUsuario;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author AT-DESARROLLO
 */
public class VentanaUsuarios extends javax.swing.JFrame {

    ControlUsuarios usuario = new ControlUsuarios();
    ArrayList<String[]> listaDatos = new ArrayList<String[]>();
    public boolean[] edit = {false, true, true, true, true, true, true};
    int ban = 0;
    TablaPermisos tbl = new TablaPermisos();
    VentanaPrincipal vprin;
    gestorMySQL gsql = new gestorMySQL();
    private int x, y;
    /**
     * Creates new form VentanaUsuarios
     */
    public VentanaUsuarios(VentanaPrincipal vprin) {
        initComponents();
        Utilidades.EstablecerIcono(this);
        this.setLocationRelativeTo(null);
        lblPerfil.setVisible(false);
        lblPersona.setVisible(false);
        txtUsuario.requestFocusInWindow();
        UsuarioEstadoFormulario(0);
        this.vprin = vprin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        pnlPermisos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtPerfil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPersona = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        lblPersona = new javax.swing.JLabel();
        txtClaveR = new javax.swing.JPasswordField();
        txtClave = new javax.swing.JPasswordField();
        btnBuscarPerfil = new javax.swing.JLabel();
        btnBuscarPersona = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPermisos = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 82, 118)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPermisos.setBackground(new java.awt.Color(26, 82, 118));
        pnlPermisos.setForeground(new java.awt.Color(26, 82, 118));
        pnlPermisos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 82, 118));
        jLabel1.setText("Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(36, 113, 163));
        txtUsuario.setBorder(null);
        txtUsuario.setSelectionColor(new java.awt.Color(31, 97, 141));
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 250, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 82, 118));
        jLabel2.setText("Estado");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        cbEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbEstado.setForeground(new java.awt.Color(21, 67, 96));
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));
        cbEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 89, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 82, 118));
        jLabel3.setText("Perfil");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtPerfil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPerfil.setForeground(new java.awt.Color(36, 113, 163));
        txtPerfil.setBorder(null);
        txtPerfil.setSelectionColor(new java.awt.Color(31, 97, 141));
        jPanel1.add(txtPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 180, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 82, 118));
        jLabel4.setText("Persona");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtPersona.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPersona.setForeground(new java.awt.Color(36, 113, 163));
        txtPersona.setBorder(null);
        txtPersona.setSelectionColor(new java.awt.Color(31, 97, 141));
        jPanel1.add(txtPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 280, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(26, 82, 118));
        jLabel5.setText("Clave");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(26, 82, 118));
        jLabel6.setText("Repetir");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));
        jPanel1.add(lblPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 61, -1, -1));
        jPanel1.add(lblPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 95, -1, -1));

        txtClaveR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtClaveR.setForeground(new java.awt.Color(36, 113, 163));
        txtClaveR.setBorder(null);
        txtClaveR.setSelectionColor(new java.awt.Color(31, 97, 141));
        jPanel1.add(txtClaveR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 120, 30));

        txtClave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtClave.setForeground(new java.awt.Color(36, 113, 163));
        txtClave.setBorder(null);
        txtClave.setSelectionColor(new java.awt.Color(31, 97, 141));
        txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClaveKeyPressed(evt);
            }
        });
        jPanel1.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 120, 30));

        btnBuscarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/lupa_1.png"))); // NOI18N
        btnBuscarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPerfilMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        btnBuscarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/lupa_1.png"))); // NOI18N
        btnBuscarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPersonaMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 260, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 240, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 340, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 120, 10));

        pnlPermisos.addTab("Datos Basicos", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblPermisos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblPermisos.setForeground(new java.awt.Color(26, 82, 118));
        tblPermisos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPermisos.setGridColor(new java.awt.Color(255, 255, 255));
        tblPermisos.setSelectionBackground(new java.awt.Color(26, 82, 118));
        tblPermisos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblPermisosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblPermisos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlPermisos.addTab("Permisos", jPanel2);

        jPanel3.add(pnlPermisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 69, -1, 327));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_over.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_over.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel6.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 64, 64));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/modificar.png"))); // NOI18N
        btnModificar.setToolTipText("Modificar");
        btnModificar.setBorderPainted(false);
        btnModificar.setContentAreaFilled(false);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setMargin(new java.awt.Insets(2, 14, 2, 5));
        btnModificar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/modificar_over.png"))); // NOI18N
        btnModificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/modificar_over.png"))); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel6.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 0, 64, 64));

        btnDescartar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar.png"))); // NOI18N
        btnDescartar.setToolTipText("Descartar");
        btnDescartar.setBorderPainted(false);
        btnDescartar.setContentAreaFilled(false);
        btnDescartar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDescartar.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnDescartar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar_over.png"))); // NOI18N
        btnDescartar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar_over.png"))); // NOI18N
        btnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarActionPerformed(evt);
            }
        });
        jPanel6.add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 0, 64, 64));

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/consultar.png"))); // NOI18N
        btnConsultar.setToolTipText("Consutar");
        btnConsultar.setBorderPainted(false);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnConsultar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/consultar_over.png"))); // NOI18N
        btnConsultar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/consultar_over.png"))); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel6.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 0, 64, 64));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/eliminar.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btnSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/eliminar_over.png"))); // NOI18N
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/eliminar_over.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel6.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 0, 64, 64));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 426, -1, -1));

        jPanel4.setBackground(new java.awt.Color(26, 82, 118));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/cerrar_1.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 5, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/minimizar.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 5, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuarios");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 656, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Map<String, String> campos = new HashMap<String, String>();
        String user = txtUsuario.getText();
        String est = cbEstado.getSelectedItem().toString();
        String idPerf = lblPerfil.getText();
        String idPers = lblPersona.getText();
        String clve = txtClave.getText();
        if(ban == 0 && clve.equals("")){
            JOptionPane.showMessageDialog(null, "Por favor ingrese una clave.", "", JOptionPane.OK_OPTION);
              
        }else{
            campos.put("user", user);
            campos.put("est", est);
            campos.put("idPerf", idPerf);
            campos.put("idPers", idPers);    
            campos.put("clve", clve);  
            if(idPers.equals("") || txtPersona.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por favor seleccione una persona.", "", JOptionPane.OK_OPTION);
                return;
            }
            if(idPerf.equals("") || txtPerfil.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por favor seleccione un perfil.", "", JOptionPane.OK_OPTION);
                return;
            }
              
            ArrayList<String[]> lista_perm = getPermisosModulos();    
            
            String ret = usuario.setUsuario(campos, lista_perm);
            //                EstadoFormulario(0);
            System.out.println("lista_perm.size()-->"+lista_perm.size());
            if(lista_perm.size()==0 && ret.equals("1")){
                int opc = JOptionPane.showConfirmDialog(null, "Al usuario creado no se le asigno ningun permiso para los modulos del sistema, ¿Desea asignarle los permisos?.", "", JOptionPane.OK_CANCEL_OPTION);                
                if(opc == JOptionPane.OK_OPTION){
                    pnlPermisos.setSelectedIndex(1);
                    return;
                }
            }
            if(user.equals(datosUsuario.datos.get(0)[0])){
                vprin.ActualizarMenu();
            }
            
            UsuarioEstadoFormulario(0);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        UsuarioEstadoFormulario(2);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescartarActionPerformed
        UsuarioEstadoFormulario(0);
    }//GEN-LAST:event_btnDescartarActionPerformed

    public void ELiminar(){
        String user = txtUsuario.getText();        
        usuario.delUsuario(user);
        UsuarioEstadoFormulario(0);
    }
    
    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        ////TRAER EL BQD CITAS 
        new ventanaBusquedaUsuario(1, "USUARIO", "", this);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        ELiminar();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            ConsultarUsuarios();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void tblPermisosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPermisosMouseReleased
        int fila = tblPermisos.getSelectedRow();
        int cola = tblPermisos.getSelectedColumn();
        System.out.println("cola--->"+cola);
        if(cola == 6){
            Object value = tblPermisos.getValueAt(fila, cola);
            System.out.println("VALOR-------"+(Boolean)value);
            if((Boolean)value){
                tblPermisos.setValueAt(true, fila, 1);
                tblPermisos.setValueAt(true, fila, 2);
                tblPermisos.setValueAt(true, fila, 3);
                tblPermisos.setValueAt(true, fila, 4);
                tblPermisos.setValueAt(true, fila, 5);
            }else{
                tblPermisos.setValueAt(false, fila, 1);
                tblPermisos.setValueAt(false, fila, 2);
                tblPermisos.setValueAt(false, fila, 3);
                tblPermisos.setValueAt(false, fila, 4);
                tblPermisos.setValueAt(false, fila, 5);
            }
        }else{
            Object value = tblPermisos.getValueAt(fila, cola);
            if((Boolean)value){
                int b = 0;
                for(int i = 1; i < 6; i++){
                    if(!(Boolean)tblPermisos.getValueAt(fila, i)){
                        b = 1;
                        break;
                    }
                }
                if(b == 0){
                    tblPermisos.setValueAt(true, fila, 6);
                }
            }else{
                if((Boolean)tblPermisos.getValueAt(fila, 6)){
                    tblPermisos.setValueAt(false, fila, 6);
                }
            }
            
        }
    }//GEN-LAST:event_tblPermisosMouseReleased

    private void txtClaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String clveNew = txtClave.getText();        
            String clveRep = txtClaveR.getText();   
            if(!clveNew.equals(clveRep) && !clveRep.equals("")){
                JOptionPane.showConfirmDialog(null, "La Contraseña ingresada no corresponde a la contraseña repetida");
                txtClave.setText("");
            }
        }
    }//GEN-LAST:event_txtClaveKeyPressed

    private void btnBuscarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPerfilMouseClicked
        if(btnBuscarPerfil.isEnabled()){
            new ventanaBusquedaPerfil(1, "IDPERFIL:-:PERFIL", "", this);
        }
        
    }//GEN-LAST:event_btnBuscarPerfilMouseClicked

    private void btnBuscarPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPersonaMouseClicked
        if(btnBuscarPersona.isEnabled()){
            int t = gsql.SELECT("SELECT IFNULL(per.pfk_tipo_documento, '') TID, IFNULL(per.pk_persona, '') IDENTIFICACION, \n"
                                + "CONCAT_WS(' ', per.primer_nombre, IFNULL(per.segundo_nombre, ''), per.primer_apellido, IFNULL(per.segundo_apellido, '')) NOMBRE, \n"
                                + "IFNULL(per.direccion, '') DIRECCION, IF(IFNULL(per.sexo, 'M')='M', 'Masculino', 'Femenino') SEXO \n"
                                + "FROM `personal` emp\n"
                                + "INNER JOIN `personas` per ON CONCAT(per.pfk_tipo_documento, per.pk_persona) = emp.pk_personal \n").size();
            if(t>0){
                new ventanaBusqueda(1, "", "TID:-:IDENTIFICACION:-:NOMBRE", this).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "No se encontraron datos");
            }
        }
    }//GEN-LAST:event_btnBuscarPersonaMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.setState(VentanaUsuarios.ICONIFIED);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        this.setLocation(this.getLocation().x + evt.getX()-x, this.getLocation().y + evt.getY()-y);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUsuarios(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscarPerfil;
    private javax.swing.JLabel btnBuscarPersona;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cbEstado;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JLabel lblPerfil;
    public javax.swing.JLabel lblPersona;
    private javax.swing.JTabbedPane pnlPermisos;
    public javax.swing.JTable tblPermisos;
    public javax.swing.JPasswordField txtClave;
    public javax.swing.JPasswordField txtClaveR;
    public javax.swing.JTextField txtPerfil;
    public javax.swing.JTextField txtPersona;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void UsuarioEstadoFormulario(int opc) {
        UsuarioEstadoBotones(opc);
        switch (opc) {
            case 0: {//DESCARTAR
                txtUsuario.setText("");
                lblPerfil.setText("");
                txtPerfil.setText("");
                lblPersona.setText("");
                txtPersona.setText("");
                txtClaveR.setText("");
                txtClave.setText("");
                cbEstado.setSelectedIndex(0);
                ////
                txtUsuario.setEnabled(true);
                txtPerfil.setEnabled(false);
                txtPersona.setEnabled(false);
                txtClaveR.setEnabled(false);
                txtClave.setEnabled(false);
                cbEstado.setEnabled(false);
                btnBuscarPerfil.setEnabled(false);
                btnBuscarPersona.setEnabled(false);
                
                pnlPermisos.setEnabledAt(1,false);
                pnlPermisos.setSelectedIndex(0);  
                CargarTablaPermisos("");
                break;
            }
            case 1: {
                txtUsuario.setEnabled(false);
                txtPerfil.setEnabled(false);
                txtPersona.setEnabled(false);
                txtClaveR.setEnabled(true);
                txtClave.setEnabled(true);
                cbEstado.setEnabled(true);
                btnBuscarPerfil.setEnabled(true);
                btnBuscarPersona.setEnabled(true);
                pnlPermisos.setEnabledAt(1,true);
                break;
            }
            case 2: {
                txtUsuario.setEnabled(false);
                txtPerfil.setEnabled(false);
                txtPersona.setEnabled(false);
                txtClaveR.setEnabled(true);
                txtClave.setEnabled(true);
                cbEstado.setEnabled(true);
                btnBuscarPerfil.setEnabled(true);
                btnBuscarPersona.setEnabled(false);
                pnlPermisos.setEnabledAt(1,true);
                break;
            }
            case 3: {
                
                txtUsuario.setEnabled(false);
                txtPerfil.setEnabled(false);
                txtPersona.setEnabled(false);
                txtClaveR.setEnabled(false);
                txtClave.setEnabled(false);
                cbEstado.setEnabled(false);
                btnBuscarPerfil.setEnabled(false);
                btnBuscarPersona.setEnabled(false);
                break;
            }
        }
    }

    public void UsuarioEstadoBotones(int opc) {
        switch (opc) {
            case 0: {//INICIO         
                btnGuardar.setEnabled(false);
                btnModificar.setEnabled(false);
                btnDescartar.setEnabled(false);
                btnConsultar.setEnabled(true);
                break;
            }
            case 1: {//NUEVO
                btnGuardar.setEnabled(true);
                btnModificar.setEnabled(false);
                btnDescartar.setEnabled(true);
                btnConsultar.setEnabled(false);
                break;
            }
            case 2: {//MODIFICAR
                btnGuardar.setEnabled(true);
                btnModificar.setEnabled(false);
                btnDescartar.setEnabled(true);
                btnConsultar.setEnabled(false);
                break;
            }
            case 3: {//CONSULTADO
                btnGuardar.setEnabled(false);
                btnModificar.setEnabled(true);
                btnDescartar.setEnabled(true);
                btnConsultar.setEnabled(false);
                break;
            }
        }
    }

    public void ConsultarUsuarios() {
        String user = txtUsuario.getText();

        if (user.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor digite un usuario");
        }

        ArrayList<String[]> Info = new ArrayList<>();
        ArrayList<String[]> lst_perm = new ArrayList<>();

        Info = usuario.getUsuario(user);

        if (Info.size() > 0) {
            String[] datos = Info.get(0);
            lblPerfil.setText(datos[0]);
            txtPerfil.setText(datos[1]);
            lblPersona.setText(datos[2]);
            txtPersona.setText(datos[3]);
            cbEstado.setSelectedItem(datos[4]);

            CargarTablaPermisos(user);
//            lst_perm = usuario.getUsuariosPermisos(user);
            if (lst_perm.size() > 0) {
                //AgregarCotizacion(lst_perm);
            }

            UsuarioEstadoFormulario(3);
            ban = 1;
        } else {
            UsuarioEstadoFormulario(1);
        }
    }

    private ArrayList<String[]> getPermisosModulos() {
        System.out.println("************************getPermisosModulos*********************");
        int rows = tblPermisos.getRowCount();
        System.out.println("rows-->" + rows);
        ArrayList<String[]> listaGuardar = new ArrayList<>();
        for (int x = 0; x < rows; x++) {
            String[] datos = listaDatos.get(x);
            Object selec = tblPermisos.getValueAt(x, 1);
            Object inser = tblPermisos.getValueAt(x, 2);
            Object updat = tblPermisos.getValueAt(x, 3);
            Object delet = tblPermisos.getValueAt(x, 4);
            Object ver = tblPermisos.getValueAt(x, 5);
            String s = (Boolean) selec ? "1" : "0",
                    i = (Boolean) inser ? "1" : "0",
                    u = (Boolean) updat ? "1" : "0",
                    d = (Boolean) delet ? "1" : "0",
                    v = (Boolean) ver ? "1" : "0";
            if(s.equals("0") && i.equals("0") && u.equals("0") && d.equals("0") && v.equals("0")){
                
            }else{
                listaGuardar.add(new String[]{datos[0], s, i, u, d, v});
                
            }
        }
        System.out.println("***************getPermisosModulos************"+listaGuardar.size()+"********");
        return listaGuardar;
    }

    public void CargarTablaPermisos(String user) {
        System.out.println("CARGAR TABLA");
        listaDatos = usuario.getPermisosUsuario(user);
        tbl.Vizualizar(this, listaDatos);

    }

}
