/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Busquedas.ventanaBusqueda;
import BaseDeDatos.gestorMySQL;
import Control.ControlPaciente;
import Control.ControlPersonal;
import Utilidades.Expresiones;
import Utilidades.Utilidades;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Acer
 */
public class VentanaPersonal extends javax.swing.JFrame {

    public VentanaPrincipal vprin;
    public gestorMySQL con;
    ControlPersonal personal = new ControlPersonal();
    public DefaultListModel modlistTelefonos;
    ArrayList<String> lista_tpoID;
    ControlPaciente paciente = new ControlPaciente();
    public String tipoId = "";
    public int enterID = 0;
    gestorMySQL gsql = new gestorMySQL();
    public int lostID = 0;
    private int x, y;   
    
    /**
     * Creates new form VentanaPersonal
     */
    public VentanaPersonal(VentanaPrincipal vprin) {
        initComponents();
        Utilidades.EstablecerIcono(this);
        this.vprin = vprin;
        this.setLocationRelativeTo(vprin);
        con = new gestorMySQL();
        modlistTelefonos = new DefaultListModel();
        lista_tpoID =  new ArrayList<>();
        //Seleccionar, CC, CE, TI, RC, NIT, NUI, PAS
        lista_tpoID.add("-1");
        lista_tpoID.add("CC");
        lista_tpoID.add("CE");
        lista_tpoID.add("TI");
        lista_tpoID.add("RC");
        lista_tpoID.add("NIT");
        lista_tpoID.add("NUI");
        lista_tpoID.add("PAS");
        EstadoFormulario(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox();
        cbTidentificacion = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        jdFNac = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstTelefonos = new javax.swing.JList();
        jLabel17 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbCargo = new javax.swing.JComboBox();
        jdFVinculacion = new com.toedter.calendar.JDateChooser();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btnConsultar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión Personal");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 82, 118)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setForeground(new java.awt.Color(21, 67, 96));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(21, 67, 96))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 67, 96));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nombres");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 99, -1));

        txtNombre1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombre1.setForeground(new java.awt.Color(21, 67, 96));
        txtNombre1.setBorder(null);
        txtNombre1.setSelectionColor(new java.awt.Color(21, 67, 96));
        jPanel4.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 570, 30));

        txtApellido1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtApellido1.setForeground(new java.awt.Color(21, 67, 96));
        txtApellido1.setBorder(null);
        txtApellido1.setSelectionColor(new java.awt.Color(21, 67, 96));
        jPanel4.add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 570, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(21, 67, 96));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Apellidos");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 99, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(21, 67, 96));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Fecha de Nacimiento");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(21, 67, 96));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Sexo");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 82, -1));

        cbSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbSexo.setForeground(new java.awt.Color(21, 67, 96));
        cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Femenino", "Masculino" }));
        jPanel4.add(cbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 140, 30));

        cbTidentificacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTidentificacion.setForeground(new java.awt.Color(21, 67, 96));
        cbTidentificacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Cédula de Ciudadania", "Cédula de Extrangeria", "Tarjeta de Identidad", "Registro Civil", "Número de Identificación Tributario", "Número Unico de Identificación", "Pasaporte" }));
        cbTidentificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbTidentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTidentificacionActionPerformed(evt);
            }
        });
        jPanel4.add(cbTidentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 240, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(21, 67, 96));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Tipo Identificación");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 67, 96));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Identificación");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 85, 20));

        txtIdentificacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIdentificacion.setForeground(new java.awt.Color(21, 67, 96));
        txtIdentificacion.setBorder(null);
        txtIdentificacion.setSelectionColor(new java.awt.Color(21, 67, 96));
        txtIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionActionPerformed(evt);
            }
        });
        txtIdentificacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdentificacionFocusLost(evt);
            }
        });
        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyReleased(evt);
            }
        });
        jPanel4.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 210, 30));

        jdFNac.setBackground(new java.awt.Color(255, 255, 255));
        jdFNac.setForeground(new java.awt.Color(21, 67, 96));
        jPanel4.add(jdFNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, 30));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, 10));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 570, 10));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 570, 10));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 640, 270));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(21, 67, 96))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(21, 67, 96));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Dirección");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 56, -1));

        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDireccion.setForeground(java.awt.Color.lightGray);
        txtDireccion.setBorder(null);
        txtDireccion.setSelectionColor(new java.awt.Color(21, 67, 96));
        jPanel5.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 290, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(21, 67, 96));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Teléfono");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCorreo.setForeground(java.awt.Color.lightGray);
        txtCorreo.setBorder(null);
        txtCorreo.setSelectionColor(new java.awt.Color(21, 67, 96));
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });
        jPanel5.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 290, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(21, 67, 96));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Correo");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelefono.setForeground(java.awt.Color.lightGray);
        txtTelefono.setBorder(null);
        txtTelefono.setSelectionColor(new java.awt.Color(21, 67, 96));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
        });
        jPanel5.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 123, 30));

        lstTelefonos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lstTelefonos.setForeground(new java.awt.Color(21, 67, 96));
        lstTelefonos.setSelectionBackground(new java.awt.Color(21, 67, 96));
        lstTelefonos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lstTelefonosMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(lstTelefonos);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 40, 110, 100));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/der_1.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 30, 30));
        jPanel5.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 290, 10));
        jPanel5.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 290, 10));
        jPanel5.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 120, 10));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 640, 160));

        jTabbedPane1.addTab("Datos Basicos", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(21, 67, 96));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Título");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 99, -1));

        txtTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(21, 67, 96));
        txtTitulo.setBorder(null);
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        jPanel3.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(21, 67, 96));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Cargo");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 82, -1));

        txtSalario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSalario.setForeground(new java.awt.Color(21, 67, 96));
        txtSalario.setBorder(null);
        txtSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSalarioKeyReleased(evt);
            }
        });
        jPanel3.add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 240, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(21, 67, 96));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Salario");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 82, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(21, 67, 96));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Fecha de Vinculación");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        cbCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Ortodoncista", "Asistente" }));
        jPanel3.add(cbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 180, 30));
        jPanel3.add(jdFVinculacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 170, 30));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 320, 10));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 240, 10));

        jTabbedPane1.addTab("Vinculación Laboral", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 670, 500));

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/consultar.png"))); // NOI18N
        btnConsultar.setToolTipText("Consutar");
        btnConsultar.setBorderPainted(false);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 64, 64));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/eliminar.png"))); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 64, 64));

        btnDescartar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar.png"))); // NOI18N
        btnDescartar.setToolTipText("Descartar");
        btnDescartar.setBorderPainted(false);
        btnDescartar.setContentAreaFilled(false);
        btnDescartar.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 64, 64));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/modificar.png"))); // NOI18N
        btnModificar.setToolTipText("Modificar");
        btnModificar.setBorderPainted(false);
        btnModificar.setContentAreaFilled(false);
        btnModificar.setMargin(new java.awt.Insets(2, 14, 2, 5));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 64, 64));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 64, 64));

        jPanel7.setBackground(new java.awt.Color(26, 82, 118));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });
        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel7MouseDragged(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/minimizar.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 30, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/cerrar_1.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 30, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gestión de Personal");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, 152, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void EstadoFormulario(int opc) {
        EstadoBotones(opc);
        switch (opc) {
            case 0: {
                txtIdentificacion.setText("");
                cbTidentificacion.setSelectedIndex(0);
                txtNombre1.setText("");
                txtApellido1.setText("");
                txtDireccion.setText("");
                txtTelefono.setText("");
                txtCorreo.setText("");
                cbSexo.setSelectedIndex(0);
                cbCargo.setSelectedIndex(0);
                txtTitulo.setText("");
                txtSalario.setText("");
                LimpiarLstTel();   
//                jdFNac.setCalendar(null);
//                
//                jdFVinculacion.setCalendar(null);
                ////
                txtIdentificacion.setEnabled(true);
                cbTidentificacion.setEnabled(true);
                txtNombre1.setEnabled(false);
                txtApellido1.setEnabled(false);
                txtDireccion.setEnabled(false);
                txtTelefono.setEnabled(false);
                txtCorreo.setEnabled(false);  
                cbSexo.setEnabled(false);
//                jdFNac.setEnabled(false);
//                jdFVinculacion.setEnabled(false);
                cbCargo.setEnabled(false);
                txtTitulo.setEnabled(false);
                txtSalario.setEnabled(false);
                
                cbTidentificacion.requestFocus();
                jTabbedPane1.setEnabledAt(1,false);
                jTabbedPane1.setSelectedIndex(0);
                break;
            }   
            case 1: {       
                txtIdentificacion.setEnabled(false);
                cbTidentificacion.setEnabled(false);   
                txtNombre1.setEnabled(true);    
                txtApellido1.setEnabled(true);
                txtDireccion.setEnabled(true);
                txtTelefono.setEnabled(true);
                txtCorreo.setEnabled(true);
                cbSexo.setEnabled(true);
                jdFNac.setEnabled(true);
                jdFVinculacion.setEnabled(true);
                cbCargo.setEnabled(true);
                txtTitulo.setEnabled(true);
                txtSalario.setEnabled(true);
                jTabbedPane1.setEnabledAt(1,true);
                txtNombre1.requestFocus();
                break;
            }
            case 2: {
                txtIdentificacion.setEnabled(false);
                cbTidentificacion.setEnabled(false);
                txtNombre1.setEnabled(true);
                txtApellido1.setEnabled(true); 
                txtDireccion.setEnabled(true);
                txtTelefono.setEnabled(true);
                txtCorreo.setEnabled(true);
                cbSexo.setEnabled(true);
                jdFNac.setEnabled(true);
                jdFVinculacion.setEnabled(true);
                cbCargo.setEnabled(true);
                txtTitulo.setEnabled(true);
                txtSalario.setEnabled(true);
                lstTelefonos.setEnabled(true);
                jTabbedPane1.setEnabledAt(1,true);
                break;
            }
            case 3: {
                txtIdentificacion.setEnabled(false);
                cbTidentificacion.setEnabled(false);
                txtNombre1.setEnabled(false);
                txtApellido1.setEnabled(false);
                txtDireccion.setEnabled(false);
                txtTelefono.setEnabled(false);
                txtCorreo.setEnabled(false);
                cbSexo.setEnabled(false);
                jdFNac.setEnabled(false);
                jdFVinculacion.setEnabled(false);
                cbCargo.setEnabled(false);
                txtTitulo.setEnabled(false);
                txtSalario.setEnabled(false);
                jTabbedPane1.setEnabledAt(1,false);
                break;
            }
        }
    }

    public void EstadoBotones(int opc) {
        switch (opc) {
            case 0: {//INICIO         
                btnGuardar.setEnabled(false);
                btnModificar.setEnabled(false);
                btnDescartar.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnConsultar.setEnabled(true);
                break;
            }
            case 1: {//NUEVO
                btnGuardar.setEnabled(true);
                btnModificar.setEnabled(false);
                btnDescartar.setEnabled(true);
                btnEliminar.setEnabled(false);
                btnConsultar.setEnabled(false);
                break;
            }
            case 2: {//MODIFICAR
                btnGuardar.setEnabled(true);
                btnModificar.setEnabled(false);
                btnDescartar.setEnabled(true);
                btnEliminar.setEnabled(true);
                btnConsultar.setEnabled(false);
                break;
            }
            case 3: {//CONSULTADO
                btnGuardar.setEnabled(false);
                btnModificar.setEnabled(true);
                btnDescartar.setEnabled(true);
                btnEliminar.setEnabled(true);
                btnConsultar.setEnabled(false);
                break;
            }
        }
    }

    public void ConsultarPersonal() {  
        String id = txtIdentificacion.getText();
        String tid = "";
        
        if(!tipoId.equals("")){  
            EstadoTIdentificacion();  
            tid = tipoId; 
            tipoId = "";  
        }else{  
            tid = lista_tpoID.get(cbTidentificacion.getSelectedIndex());
        }        
        
        boolean pac = (paciente.getPaciente(id, tid).size() > 0);  
        if(pac){            
            JOptionPane.showMessageDialog(rootPane, "La identificación digitada ya se encuentra registrada para un paciente. \nPor favor verifique la información e intentelo nuevamente.");
            txtIdentificacion.setText("");
            //txtId.requestFocusInWindow();
            return;
        }
        if(id.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor digite una identificación");
            //txtIdentificacion.requestFocusInWindow();
            return;
        }
        
        if(tid.equals("Seleccionar")) {
            //cbTidentificacion.requestFocusInWindow();
            JOptionPane.showMessageDialog(rootPane, "Por favor escoja un tipo de identificación");            
            return;
        }
        ArrayList<String[]> Info = new ArrayList<>();
        Info = personal.getPersonal(id, tid);

        //RECORRO LISTA CON INFO
        
        if(Info != null){
            if(Info.size() > 0){
                String[] datos = Info.get(0);
                txtNombre1.setText(datos[0]);
                txtApellido1.setText(datos[1]);
                txtDireccion.setText(datos[2]);
                cbSexo.setSelectedItem(datos[3]);
                jdFNac.setCalendar(formatString(datos[4]));
                txtCorreo.setText(datos[5]);
                String[] tels = (datos[6].equals("")?null:datos[6].split("<>"));
                if(tels != null){
                    System.out.println("tels--->"+tels.length);
                    for(int i = 0; i < tels.length; i++){
                        modlistTelefonos.addElement(tels[i]);
                    }  
                    lstTelefonos.setModel(modlistTelefonos);
                }

                txtTitulo.setText(datos[7]);
                cbCargo.setSelectedItem(datos[8]);
                txtSalario.setText(datos[9]);
                jdFVinculacion.setCalendar(formatString(datos[10]));
                EstadoFormulario(3);
            }else{
                EstadoFormulario(1);
            }            
        } else {
            EstadoFormulario(1);
        }
    }

    private void btnDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescartarActionPerformed
        // TODO add your handling code here:
        EstadoFormulario(0);
    }//GEN-LAST:event_btnDescartarActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtIdentificacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if(!txtIdentificacion.getText().equals("")){
                enterID = 1;
                ConsultarPersonal();
            }
        }
    }//GEN-LAST:event_txtIdentificacionKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
   
        String id = txtIdentificacion.getText();
        String tid = cbTidentificacion.getSelectedItem().toString();
        tid = lista_tpoID.get(cbTidentificacion.getSelectedIndex());
        
        String n1 = Utilidades.CodificarElemento(txtNombre1.getText().toUpperCase());
        String a1 = Utilidades.CodificarElemento(txtApellido1.getText().toUpperCase());
        String sex = cbSexo.getSelectedItem().toString();
        System.out.println("jdFNac-->"+jdFNac.toString()+"//");
        System.out.println("jdFNac-->"+jdFNac.getCalendar()+"//");
        if (jdFNac.getCalendar() == null) {
            JOptionPane.showMessageDialog(rootPane, "Por favor llenar el campo de fecha de nacimiento");
            jdFNac.requestFocusInWindow();
            return;
        }
        if (jdFVinculacion.getCalendar() == null) {
            JOptionPane.showMessageDialog(rootPane, "Por favor llenar el campo de fecha de vinculación");
            jTabbedPane1.setSelectedIndex(1);
            jdFVinculacion.requestFocusInWindow();
            return;
        }
        String fnac = sdf.format(jdFNac.getCalendar().getTime());
        String cor = txtCorreo.getText();
        String dir = Utilidades.CodificarElemento(txtDireccion.getText());
        String tel = "";
        for(int i = 0; i < modlistTelefonos.size(); i++){
            tel+=(tel.equals("")?"":"<>")+modlistTelefonos.getElementAt(i);
        } 

        String tit = Utilidades.CodificarElemento(txtTitulo.getText());
        String car = cbCargo.getSelectedItem().toString();
        String sal = txtSalario.getText();
        String fvin = sdf.format(jdFVinculacion.getCalendar().getTime());
        if (n1.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor digite el nombre del empleado");
            return;
        }
        if (a1.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor digite el apellido del empleado");
            return;
        }
        
        Map<String, String> campos = new HashMap<String, String>();
        campos.put("id", id);
        campos.put("tid", tid);
        campos.put("noms", n1);
        campos.put("apes", a1);
        campos.put("dir", dir);
        campos.put("sxo", sex);
        campos.put("fnac", fnac);
        campos.put("cor", cor);  
        campos.put("tel", tel);
        
        campos.put("tit", tit);
        campos.put("car", car);
        campos.put("sal", sal);
        campos.put("fvin", fvin);
        

        personal.setPersonal(campos);
        EstadoFormulario(0);

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        EstadoFormulario(2);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtIdentificacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdentificacionFocusLost
        if(!txtIdentificacion.getText().equals("")){
            if(enterID == 0){ 
                lostID = 1;    
                ConsultarPersonal();
            }else{  
                enterID = 0;
            }  
        }
    }//GEN-LAST:event_txtIdentificacionFocusLost

    private void txtSalarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalarioKeyReleased
        validarCampoEntero(txtSalario);  
    }//GEN-LAST:event_txtSalarioKeyReleased

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
//        int t = gsql.SELECT("SELECT IFNULL(per.pfk_tipo_documento, '') TID, IFNULL(per.pk_persona, '') IDENTIFICACION, \n"
//                            + "CONCAT_WS(' ', per.primer_nombre, IFNULL(per.segundo_nombre, ''), per.primer_apellido, IFNULL(per.segundo_apellido, '')) NOMBRE, \n"
//                            + "IFNULL(per.direccion, '') DIRECCION, IF(IFNULL(per.sexo, 'M')='M', 'Masculino', 'Femenino') SEXO \n"
//                            + "FROM `personal` emp\n"
//                            + "INNER JOIN `personas` per ON CONCAT(per.pfk_tipo_documento, per.pk_persona) = emp.pk_personal \n").size();
//        if(t>0){
            new ventanaBusqueda(1, null, "TID:-:IDENTIFICACION", this);
//        }else{
//            JOptionPane.showMessageDialog(null, "No se encontraron datos");
//        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String id = txtIdentificacion.getText();
        String tid = lista_tpoID.get(cbTidentificacion.getSelectedIndex());
        personal.delPersonal(id, tid);
        EstadoFormulario(0);   
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cbTidentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTidentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTidentificacionActionPerformed

    private void lstTelefonosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTelefonosMousePressed
        if (evt.getClickCount() == 2) {
            if(lstTelefonos.isEnabled()){
                modlistTelefonos.remove(lstTelefonos.getSelectedIndex());
                lstTelefonos.setModel(modlistTelefonos);
            }
        }
    }//GEN-LAST:event_lstTelefonosMousePressed

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyPressed
        if (KeyEvent.VK_ENTER  == evt.getKeyCode() || KeyEvent.VK_SPACE == evt.getKeyCode()) {
            String dat = txtTelefono.getText();
            System.out.println("*************telefono****************"+dat);
            if (!estaSeleccionado(modlistTelefonos, dat) && !dat.equals("") && (dat.length()==7 || dat.length() == 10)) {
                modlistTelefonos.addElement(dat);
                lstTelefonos.setModel(modlistTelefonos);
                txtTelefono.setText("");
                txtTelefono.requestFocusInWindow();
            }else{
                System.out.println("NO SELECCIONADO--------------");
            }
        }
    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        if(validarCorreo(txtCorreo)){
            jTabbedPane1.setSelectedIndex(1);
            //txtTitulo.requestFocus();
        }
    }//GEN-LAST:event_txtCorreoFocusLost

    private void txtIdentificacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyReleased
        Expresiones.procesarSoloNumeros(txtIdentificacion);
    }//GEN-LAST:event_txtIdentificacionKeyReleased

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        Expresiones.procesarSoloNumeros(txtTelefono); 
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.setState(VentanaPersonal.ICONIFIED);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel7MousePressed

    private void jPanel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseDragged
        this.setLocation(this.getLocation().x + evt.getX()-x, this.getLocation().y + evt.getY()-y);
    }//GEN-LAST:event_jPanel7MouseDragged

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        String dat = txtTelefono.getText();
        System.out.println("*************telefono****************" + dat);
        if (!estaSeleccionado(modlistTelefonos, dat) && !dat.equals("") && (dat.length() == 7 || dat.length() == 10)) {
            modlistTelefonos.addElement(dat);
            lstTelefonos.setModel(modlistTelefonos);
            txtTelefono.setText("");
            txtTelefono.requestFocusInWindow();
        } else if (dat.length() < 7) {
            JOptionPane.showMessageDialog(rootPane, "Por favor Digite correctamente el número de telefono.");
        } else if (dat.length() < 9) {
            JOptionPane.showMessageDialog(rootPane, "Por favor Digite correctamente el número de celular.");
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void validarCampoEntero(JTextField txtEntero) {
        String tel = txtEntero.getText();
        String taux = "";
        Pattern pat = Pattern.compile("^[0-9]+$");
        Matcher mat = pat.matcher(tel);
        if (mat.matches()) {
            System.out.println("SI");
        } else {
            System.out.println("NO");
            for (int i = 0; i < tel.length(); i++) {
                //if(pn.charAt(i)== '0'||pn.charAt(i)== '1'||pn.charAt(i)== '2'||pn.charAt(i)== '3'||pn.charAt(i)== '4'||pn.charAt(i)== '5'||pn.charAt(i)== '6'||pn.charAt(i)== '7'||pn.charAt(i)== '8'||pn.charAt(i)== '9' );
                System.out.println("dato-->" + tel.charAt(i) + " ****" + (int) tel.charAt(i));
                if (tel.charAt(i) > 47 && tel.charAt(i) < 56) {
                    taux += tel.charAt(i);
                }
            }
            txtEntero.setText(taux);
        }
    }

    private boolean validarCorreo(JTextField txt) {
        Pattern pat = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,4})$");
        Matcher mat = pat.matcher(txt.getText());
        boolean ret = false;
        if (mat.matches()) {
            System.out.println("SI");
            ret = true;
        } else {
            txt.setText("");
            System.out.println("NO");
            JOptionPane.showMessageDialog(rootPane, "Escriba un correo electronico valido");
            //txt.requestFocus();
        }
        return ret;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPersonal(null).setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    public javax.swing.JComboBox cbCargo;
    public javax.swing.JComboBox cbSexo;
    public javax.swing.JComboBox cbTidentificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jdFNac;
    private com.toedter.calendar.JDateChooser jdFVinculacion;
    private javax.swing.JList lstTelefonos;
    public javax.swing.JTextField txtApellido1;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtIdentificacion;
    public javax.swing.JTextField txtNombre1;
    public javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtTelefono;
    public javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

  
    private Calendar formatString(String f) {
       Date fecha = new Date(Integer.parseInt(f.split("/")[2])-1900, Integer.parseInt(f.split("/")[1]) - 1, Integer.parseInt(f.split("/")[0]));
       SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); 
       Calendar cal = Calendar.getInstance();
       cal.setTime(fecha);
       return cal;
   }
    
    private boolean estaSeleccionado(DefaultListModel modelo, String valor) {
       for (int i = 0; i < modelo.size(); i++) {
           if (modelo.getElementAt(i).equals(valor)) {
               return true;
           }
       }
       return false;
    }
    
    private void EstadoTIdentificacion() {
        System.out.println("******************EstadoTIdentificacion***************"+tipoId+"**********");
        for(int i = 0; i < lista_tpoID.size(); i++){
            System.out.println("lista_tpoID.get("+i+")-->"+lista_tpoID.get(i));
            if(lista_tpoID.get(i).equals(tipoId)){  
                cbTidentificacion.setSelectedIndex(i);
                break;
            }  
        }  
        System.out.println("**********************END EstadoTIdentificacion*************************");
    }
    
    private void LimpiarLstTel(){        
        modlistTelefonos.removeAllElements();
        lstTelefonos.setModel(modlistTelefonos);
        lstTelefonos.setEnabled(false);
    }
    
}
