/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;
import BaseDeDatos.gestorMySQL;
import Busquedas.ventanaBusquedaArticulo;
import Utilidades.Expresiones;
import Utilidades.Utilidades;
import Utilidades.datosUsuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;



/**
 *
 * @author 10
 */
public class VentanaConsultarArticulo extends javax.swing.JFrame {
private gestorMySQL gsql;
public ArrayList <String> consultas;
private int x, y;
    /**
     * Creates new form VentanaConsultarArticulo
     */
    public VentanaConsultarArticulo() {
        initComponents();
        Utilidades.EstablecerIcono(this);
        this.setLocationRelativeTo(null);
        gsql= new gestorMySQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcodArticulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNomArticulo = new javax.swing.JLabel();
        txtNombreArticulo = new javax.swing.JTextField();
        lblValoArticulo = new javax.swing.JLabel();
        txtValorArticulo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        bntAtras = new javax.swing.JButton();
        btnEliminaArticulo = new javax.swing.JButton();
        btnCrearArticulo = new javax.swing.JButton();
        btnBuscarArticulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrar Articulos");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 82, 118)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomArticulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNomArticulo.setForeground(new java.awt.Color(21, 67, 141));
        lblNomArticulo.setText("Nombre del Articulo");
        jPanel1.add(lblNomArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        txtNombreArticulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombreArticulo.setForeground(new java.awt.Color(21, 67, 141));
        txtNombreArticulo.setBorder(null);
        jPanel1.add(txtNombreArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 330, 30));

        lblValoArticulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValoArticulo.setForeground(new java.awt.Color(21, 67, 141));
        lblValoArticulo.setText("Valor $");
        jPanel1.add(lblValoArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 60, -1));

        txtValorArticulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtValorArticulo.setForeground(new java.awt.Color(21, 67, 141));
        txtValorArticulo.setBorder(null);
        txtValorArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorArticuloKeyReleased(evt);
            }
        });
        jPanel1.add(txtValorArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 110, 30));

        jPanel3.setBackground(new java.awt.Color(26, 82, 118));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/minimizar.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/cerrar_1.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 30, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Articulos");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, 152, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 330, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 110, 10));

        bntAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar.png"))); // NOI18N
        bntAtras.setToolTipText("Atras");
        bntAtras.setBorderPainted(false);
        bntAtras.setContentAreaFilled(false);
        bntAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(bntAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 64, 64));
        bntAtras.getAccessibleContext().setAccessibleDescription("64");

        btnEliminaArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/eliminar.png"))); // NOI18N
        btnEliminaArticulo.setToolTipText("Eliminar");
        btnEliminaArticulo.setBorderPainted(false);
        btnEliminaArticulo.setContentAreaFilled(false);
        btnEliminaArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaArticuloActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminaArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 64, 64));
        btnEliminaArticulo.getAccessibleContext().setAccessibleDescription("64");

        btnCrearArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_1.png"))); // NOI18N
        btnCrearArticulo.setToolTipText("Crear");
        btnCrearArticulo.setBorderPainted(false);
        btnCrearArticulo.setContentAreaFilled(false);
        btnCrearArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearArticuloActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 64, 64));
        btnCrearArticulo.getAccessibleContext().setAccessibleDescription("64");

        btnBuscarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/consultar.png"))); // NOI18N
        btnBuscarArticulo.setToolTipText("Buscar");
        btnBuscarArticulo.setBorderPainted(false);
        btnBuscarArticulo.setContentAreaFilled(false);
        btnBuscarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarArticuloActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 64, 64));
        btnBuscarArticulo.getAccessibleContext().setAccessibleDescription("64");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearArticuloActionPerformed
        String NombreArticulo = Utilidades.decodificarElemento(txtNombreArticulo.getText());
        String ValorArticulo= txtValorArticulo.getText();
        String Sql;
        
        if (NombreArticulo.isEmpty()){
        JOptionPane.showMessageDialog(null,"Porfavor ingrese el Nombre del Articulo");
        return;
        };
        if (ValorArticulo.isEmpty()){
        JOptionPane.showMessageDialog(null,"Porfavor ingrese el Valor del Articulo");
        return;
        };
        
        
        String con ="SELECT  IFNULL(MAX(`pk_articulo`), 0)+1 FROM articulo";
        String pk_a = gsql.unicoDato(con);
        System.out.println("pk articulo-----"+ pk_a);
        try {
            ArrayList<String> consulta = new ArrayList<>();
            System.out.println("pk articulo-----"+ pk_a);
            Sql = "INSERT INTO articulo VALUES";
            Sql += "(" + pk_a + ",'" + NombreArticulo + "','" + ValorArticulo + "','" + datosUsuario.datos.get(0)[0] + "', NOW(), NULL, NULL)";
            consulta.add(Sql);
            gsql.EnviarConsultas(consulta);
            System.out.println("entro al insert");
            JOptionPane.showMessageDialog(null, "Articulo Creado");

        } catch (Exception e) {
           e.printStackTrace();
        }
        limpiarArticulo();
    }//GEN-LAST:event_btnCrearArticuloActionPerformed

    private void bntAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAtrasActionPerformed
        limpiarArticulo();
    }//GEN-LAST:event_bntAtrasActionPerformed

    private void btnBuscarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarArticuloActionPerformed
      
       new Busquedas.ventanaBusquedaArticulo(this).setVisible(true);
    }//GEN-LAST:event_btnBuscarArticuloActionPerformed

    private void txtValorArticuloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorArticuloKeyReleased
       Expresiones.procesarSoloNumeros(txtValorArticulo);
    }//GEN-LAST:event_txtValorArticuloKeyReleased

    private void btnEliminaArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaArticuloActionPerformed
        String pk_articulo = lblcodArticulo.getText();
        System.out.println("pkar----" + pk_articulo);

        String sq = "SELECT `pk_articulo` FROM `articulo` WHERE `pk_articulo` ='" + pk_articulo + "'";
        String coda = gsql.unicoDato(sq);

        String sql = "SELECT c.`fk_articulo` FROM `conceptos` c INNER JOIN  `articulo` ar\n"
                + "WHERE c.`fk_articulo` ='" + coda + "'";
        String rcod = gsql.unicoDato(sql);
        System.out.println("rcord----" + rcod);
        
        
        
        if (pk_articulo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un articulo para eliminarlo");
            return;
        }

        if (coda.equals(rcod)) {
            JOptionPane.showMessageDialog(null, "El articulo no se puede eliminar");
            limpiarArticulo();
            return;
        }

       
        if (coda != null) {
            try {
                System.out.println("cod----" + coda);
                consultas = new ArrayList<>();
                consultas.add("DELETE FROM articulo WHERE `pk_articulo`='" + coda + "'");
                int opcion = JOptionPane.showConfirmDialog(null, "Desea elinimar el Articulo");
                if (opcion == JOptionPane.YES_OPTION) {
                    if (gsql.EnviarConsultas(consultas)) {
                        JOptionPane.showMessageDialog(null, "Articulo Eliminado");
                    } else {
                        JOptionPane.showMessageDialog(null, "No se pudo eliminar el Articulo");
                    }
                }

            } catch (Exception e) {
            }
            limpiarArticulo();

        } else {
            JOptionPane.showMessageDialog(null, "El Articlo no se puede Eliminar");
            limpiarArticulo();
        }
    }//GEN-LAST:event_btnEliminaArticuloActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setState(VentanaConsultarArticulo.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        this.setLocation(this.getLocation().x + evt.getX()-x, this.getLocation().y + evt.getY()-y);
    }//GEN-LAST:event_jPanel3MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsultarArticulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bntAtras;
    public javax.swing.JButton btnBuscarArticulo;
    public javax.swing.JButton btnCrearArticulo;
    public javax.swing.JButton btnEliminaArticulo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblNomArticulo;
    private javax.swing.JLabel lblValoArticulo;
    public javax.swing.JLabel lblcodArticulo;
    public javax.swing.JTextField txtNombreArticulo;
    public javax.swing.JTextField txtValorArticulo;
    // End of variables declaration//GEN-END:variables

    private void limpiarArticulo() {
       btnCrearArticulo.setEnabled(true);
       txtNombreArticulo.setText("");
       txtValorArticulo.setText("");
       lblcodArticulo.setText("");
       
       
        
    }
}
