/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Control.ControlPaciente;
import Utilidades.Utilidades;
import java.util.ArrayList;
import java.util.Map;

/**
 *
 * @author Acer
 */
public class ventanaObsPac extends javax.swing.JFrame {
    VistaPaciente vpac;
    Map<String, String> datos;
    ControlPaciente paciente = new ControlPaciente();
    Utilidades util = new Utilidades();
    /**
     * Creates new form ventanaObsPac
     */
    public ventanaObsPac(){
        initComponents();
        Utilidades.EstablecerIcono(this);
    }
    
    public ventanaObsPac(VistaPaciente vpac, Map<String, String> datos) {
        initComponents();
        Utilidades.EstablecerIcono(this);
        EstadoVent();
        System.out.println("*********************ventanaObsPac*************************");
        this.vpac = vpac;
        this.datos = datos;
        this.setLocationRelativeTo(null);
        if(datos.get("obs").equals("")){
            txtObservacion.setEnabled(true);
            btnGuardarObs.setVisible(true);
        }else{
            txtObservacion.setText(datos.get("obs"));
            txtObservacion.setEnabled(false);
            btnGuardarObs.setVisible(false);
        }
    }

    public void EstadoVent(){
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        btnGuardarObs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Observación");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        jScrollPane1.setViewportView(txtObservacion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 28, 340, 168));

        btnGuardarObs.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardarObs.setText("Guardar");
        btnGuardarObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarObsActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarObsActionPerformed
        String obs = txtObservacion.getText().trim();
        if(!obs.equals("")){
            ////obs = util.CodificarElemento(obs);
            datos.put("obs", obs);            
            paciente.setObservacion(datos);
            this.dispose();
            vpac.LlenarTablaTratamiento();
        }
    }//GEN-LAST:event_btnGuardarObsActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaObsPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaObsPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaObsPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaObsPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaObsPac();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarObs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtObservacion;
    // End of variables declaration//GEN-END:variables
}
