/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;
import Busquedas.ventanaBusquedaTratamientos;
import Utilidades.Expresiones;
import Utilidades.Utilidades;
import javax.swing.JOptionPane;
/**
 *
 * @author 10
 */
public class VentanaModificarTrata extends javax.swing.JFrame {
    private int x, y;
    public int banBQDTrat = 0;
    VistaPaciente vp;
    VentanaPacienteAux vpx;
    public int ban = 0;
    int fila = -1;
    /**
     * Creates new form VentanaModificarTrata
     */
    
    public VentanaModificarTrata(){
     Utilidades.EstablecerIcono(this);
    }
    
    public VentanaModificarTrata(VistaPaciente vp, int fila) {
     
        initComponents();
        Utilidades.EstablecerIcono(this);
        this.setLocationRelativeTo(null);
        lblFila.setVisible(false);
        lblIdTratamiento.setVisible(false);
        this.vp = vp;
        ban = 0;
        txtDiferidas.setText("3");
        this.fila = fila;
        System.out.println("fila-->"+fila);
        if(fila >= 0){
            LlenarFormulario();
        }else{
            LimpiarFormulario();
        }
    }
    
     public VentanaModificarTrata(VentanaPacienteAux vpx, int fila) {
        initComponents();
        this.setLocationRelativeTo(null);
        lblFila.setVisible(false);
        lblIdTratamiento.setVisible(false);
        this.vpx = vpx;
        txtDiferidas.setText("3");
        this.fila = fila;
        ban = 1;
        System.out.println("fila-->"+fila);
        if(fila >= 0){
            LlenarFormulario();
        }else{
            LimpiarFormulario();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblBsqTratamiento = new javax.swing.JLabel();
        txtTratamiento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtCostoTotal = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtCuotaIni = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDiferidas = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtCuota = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        btnGuardar1 = new javax.swing.JButton();
        btnDescartar1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblIdTratamiento = new javax.swing.JLabel();
        lblFila = new javax.swing.JLabel();
        lblIdTratamiento1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 82, 118)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(26, 82, 118));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/cerrar_1.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/minimizar.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cotización por Paciente");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 30));

        lblBsqTratamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/lupa_1.png"))); // NOI18N
        lblBsqTratamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBsqTratamientoMouseClicked(evt);
            }
        });
        jPanel1.add(lblBsqTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 30, 30));

        txtTratamiento.setEditable(false);
        txtTratamiento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTratamiento.setForeground(new java.awt.Color(21, 67, 96));
        txtTratamiento.setBorder(null);
        jPanel1.add(txtTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 360, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 67, 96));
        jLabel1.setText("Costo Total");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 360, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 67, 96));
        jLabel2.setText("Tratamiento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtCostoTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCostoTotal.setForeground(new java.awt.Color(21, 67, 96));
        txtCostoTotal.setBorder(null);
        txtCostoTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCostoTotalKeyReleased(evt);
            }
        });
        jPanel1.add(txtCostoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 180, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 180, 10));

        txtCuotaIni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCuotaIni.setForeground(new java.awt.Color(21, 67, 96));
        txtCuotaIni.setBorder(null);
        txtCuotaIni.setEnabled(false);
        txtCuotaIni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCuotaIniKeyReleased(evt);
            }
        });
        jPanel1.add(txtCuotaIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 180, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(21, 67, 96));
        jLabel4.setText("Cuota Inicial");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(21, 67, 96));
        jLabel5.setText("Cuotas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 50, -1));

        txtDiferidas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDiferidas.setForeground(new java.awt.Color(21, 67, 96));
        txtDiferidas.setBorder(null);
        txtDiferidas.setEnabled(false);
        txtDiferidas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiferidasKeyReleased(evt);
            }
        });
        jPanel1.add(txtDiferidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 70, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 70, 10));

        txtCuota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCuota.setForeground(new java.awt.Color(21, 67, 96));
        txtCuota.setBorder(null);
        txtCuota.setEnabled(false);
        txtCuota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCuotaKeyReleased(evt);
            }
        });
        jPanel1.add(txtCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 180, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(21, 67, 96));
        jLabel6.setText("Cuotas de");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 180, 10));

        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar.png"))); // NOI18N
        btnGuardar1.setToolTipText("Guardar");
        btnGuardar1.setBorderPainted(false);
        btnGuardar1.setContentAreaFilled(false);
        btnGuardar1.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnGuardar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_over.png"))); // NOI18N
        btnGuardar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_over.png"))); // NOI18N
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 64, 64));

        btnDescartar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar.png"))); // NOI18N
        btnDescartar1.setToolTipText("Descartar");
        btnDescartar1.setBorderPainted(false);
        btnDescartar1.setContentAreaFilled(false);
        btnDescartar1.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnDescartar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar_over.png"))); // NOI18N
        btnDescartar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar_over.png"))); // NOI18N
        btnDescartar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDescartar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 64, 64));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(21, 67, 96));
        jLabel7.setText("Diferida en");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 90, -1));
        jPanel1.add(lblIdTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, 10));
        jPanel1.add(lblFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 10, 10));
        jPanel1.add(lblIdTratamiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 0, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        this.setState(VentanaModificarTrata.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        this.setLocation(this.getLocation().x + evt.getX()-x, this.getLocation().y + evt.getY()-y);
    }//GEN-LAST:event_jPanel5MouseDragged

    private void lblBsqTratamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBsqTratamientoMouseClicked
        if(banBQDTrat == 0){
            //new ventanaBusquedaPaciente(1, "IDENTIFICACION:-:NOMBRE", estadoch, this);
            if(lblBsqTratamiento.isEnabled())
             new ventanaBusquedaTratamientos(1, "ID:-:TRATAMIENTO", "", this, 2);
        }
    }//GEN-LAST:event_lblBsqTratamientoMouseClicked

    private void txtCostoTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoTotalKeyReleased
        String costo = txtCostoTotal.getText();
        String valorsin = costo.indexOf(".")>-1?costo.replace(".", ""):costo;
        System.out.println("valorsin--->"+valorsin);
        String dato = Expresiones.procesarSoloNum(valorsin);
        if(dato.length()>=9){
            dato  = dato.substring(0, 9);
        }
        dato = Utilidades.MascaraMoneda(dato);
        txtCostoTotal.setText(dato);
    }//GEN-LAST:event_txtCostoTotalKeyReleased

    private void txtCuotaIniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuotaIniKeyReleased
        String cuotai = txtCuotaIni.getText();
        String valorsin = cuotai.indexOf(".")>-1?cuotai.replace(".", ""):cuotai;
        System.out.println("valorsin--->"+valorsin);
        String dato = Expresiones.procesarSoloNum(valorsin);
        if(dato.length()>=9){
            dato  = dato.substring(0, 9);
        }
        dato = Utilidades.MascaraMoneda(dato);
        txtCuotaIni.setText(dato);
    }//GEN-LAST:event_txtCuotaIniKeyReleased

    private void txtDiferidasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiferidasKeyReleased
        System.out.println("txtDiferidas.getText()-->"+txtDiferidas.getText());
        System.out.println("txtDiferidas.getText().length()-->"+txtDiferidas.getText().length());
        Expresiones.procesarSoloNumeros(txtDiferidas);
        if(txtDiferidas.getText().length()>=2){
            txtDiferidas.setText(txtDiferidas.getText().substring(0, 1));
        }
    }//GEN-LAST:event_txtDiferidasKeyReleased

    private void txtCuotaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuotaKeyReleased
        String cuota = txtCuota.getText();
        String valorsin = cuota.indexOf(".")>-1?cuota.replace(".", ""):cuota;
        System.out.println("valorsin--->"+valorsin);
        String dato = Expresiones.procesarSoloNum(valorsin);
        if(dato.length()>=9){
            dato  = dato.substring(0, 9);
        }
        dato = Utilidades.MascaraMoneda(dato);
        txtCuota.setText(dato);
    }//GEN-LAST:event_txtCuotaKeyReleased

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        if(lblIdTratamiento.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Por favor seleccione un tratamiento para realizar la operación.");
            return;
        }
        if(txtCostoTotal.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Por favor ingrese el costo total.");
            return;
        }
        if(txtCuotaIni.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Por favor ingrese la cuota inicial.");
            return;
        }
        if(txtCuota.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Por favor ingrese la cuota.");
            return;
        }
        int opc = -1;
        if(Integer.parseInt(txtCostoTotal.getText().replace(".", "")) > 0 && Integer.parseInt(txtCostoTotal.getText().replace(".", "")) < 1000000){
            opc = JOptionPane.showConfirmDialog(this, "¿Esta seguro de modificar el valor del tratamiento a "+txtCostoTotal.getText()+"?", "Consulta", JOptionPane.YES_NO_OPTION);
            if(opc == JOptionPane.NO_OPTION)
                return;
        }
        
        if(Integer.parseInt(txtCuotaIni.getText().replace(".", "")) > Integer.parseInt(txtCostoTotal.getText().replace(".", "")) && Integer.parseInt(txtCostoTotal.getText().replace(".", "")) > 0){
            JOptionPane.showMessageDialog(this, "La cuota Inicial no puede ser mayor que el costo Total del tratamiento.");
            return;
        }

        if(ban == 0){//PACIENTE
            //vp.agre
            //DATOS 0-->idTrat , 1--> TRAT, 2--> CostoTotal, 3-->CuotaIni, 4-->diferidas, 5 --> cuota, 6-->(0 si es nuevo, 1 si ya esta en la tabla), 7-->(VACIO)
            System.out.println("fila------"+fila);
            if(fila>=0){
                
                System.out.println("estoy AQUI!!");
                String[] datos = new String[]{lblIdTratamiento.getText(), txtTratamiento.getText(),
                    txtCostoTotal.getText(), txtCuotaIni.getText(), txtDiferidas.getText(),
                    txtCuota.getText(), vp.listaTratamiento.get(fila)[6],vp.listaTratamiento.get(fila)[7],
                    vp.listaTratamiento.get(fila)[8],vp.listaTratamiento.get(fila)[9],vp.listaTratamiento.get(fila)[10], vp.listaTratamiento.get(fila)[11]};
                vp.datos = datos;
                vp.ActualizarTratamiento(fila);
            }
//            else{
//                String[] datos = new String[]{lblIdTratamiento.getText(), txtTratamiento.getText(),
//                    txtCostoTotal.getText(), txtCuotaIni.getText(), txtDiferidas.getText(),
//                    txtCuota.getText(), "0", ""};
//                vp.datos = datos;
//                vp.AgregarCotizacion();
//            }

//        }else{
//            if(fila>0){
//                String[] datos = new String[]{lblIdTratamiento.getText(), txtTratamiento.getText(),
//                    txtCostoTotal.getText(), txtCuotaIni.getText(), txtDiferidas.getText(),
//                    txtCuota.getText(), "0", ""};
//                vpx.datos = datos;
//                vpx.ActualizarCotizacion(fila);
//            }
////            else{
////                String[] datos = new String[]{lblIdTratamiento.getText(), txtTratamiento.getText(),
////                    txtCostoTotal.getText(), txtCuotaIni.getText(), txtDiferidas.getText(),
////                    txtCuota.getText(), "0", ""};
////                vpx.datos = datos;
////                vpx.AgregarCotizacion();
////            }
        }
        
        this.dispose();
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnDescartar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescartar1ActionPerformed
        LimpiarFormulario();
    }//GEN-LAST:event_btnDescartar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarTrata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarTrata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarTrata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarTrata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaModificarTrata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescartar1;
    private javax.swing.JButton btnGuardar1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblBsqTratamiento;
    private javax.swing.JLabel lblFila;
    public javax.swing.JLabel lblIdTratamiento;
    public javax.swing.JLabel lblIdTratamiento1;
    public javax.swing.JTextField txtCostoTotal;
    public javax.swing.JTextField txtCuota;
    public javax.swing.JTextField txtCuotaIni;
    public javax.swing.JTextField txtDiferidas;
    public javax.swing.JTextField txtTratamiento;
    // End of variables declaration//GEN-END:variables

private void LimpiarFormulario() {
        lblIdTratamiento.setText("");
        txtTratamiento.setText("");
        txtCostoTotal.setText("");
        txtCuotaIni.setText("");
        txtDiferidas.setText("");
        txtCuota.setText("");
        
        txtCostoTotal.setEnabled(true);
        txtCuotaIni.setEnabled(true);
        txtDiferidas.setEnabled(true);
        txtCuota.setEnabled(true);
        
    }
private void LlenarFormulario() {
        lblBsqTratamiento.setEnabled(false);
        System.out.println("fila-->"+fila);
        if(vpx ==  null){
        lblIdTratamiento.setText(vp.listaTratamiento.get(fila)[0]);
        txtTratamiento.setText(vp.listaTratamiento.get(fila)[1]);
        txtCostoTotal.setText(Utilidades.MascaraMoneda(vp.listaTratamiento.get(fila)[2].replace(".", "")));
        txtCuotaIni.setText(Utilidades.MascaraMoneda(vp.listaTratamiento.get(fila)[3].replace(".", "")));
        txtDiferidas.setText(vp.listaTratamiento.get(fila)[4]);
        txtCuota.setText(Utilidades.MascaraMoneda(vp.listaTratamiento.get(fila)[5].replace(".", "")));
        
        }else{
            lblIdTratamiento.setText(vp.listaTratamiento.get(fila)[0]);
            txtTratamiento.setText(vp.listaTratamiento.get(fila)[1]);
            txtCostoTotal.setText(Utilidades.MascaraMoneda(vp.listaTratamiento.get(fila)[2].replace(".", "")));
            txtCuotaIni.setText(Utilidades.MascaraMoneda(vp.listaTratamiento.get(fila)[3].replace(".", "")));
            txtDiferidas.setText(vp.listaTratamiento.get(fila)[4]);
            txtCuota.setText(Utilidades.MascaraMoneda(vp.listaTratamiento.get(fila)[5].replace(".", "")));
        }
        txtCostoTotal.setEnabled(true);
        txtCuotaIni.setEnabled(true);
        txtDiferidas.setEnabled(true);
        txtCuota.setEnabled(true);
    }





}
