/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import HISTORIA_CLINICA.tiposDeConvencion;
import Utilidades.Expresiones;
import Utilidades.Utilidades;  
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class VentanaAdicionarConceptos extends javax.swing.JFrame {

    ventanaConsultarF vf;
    public int x,y;
    public int banBQDConc = 0;
    int fila = -1;
    public ArrayList<String> Listaconceptos;
    /**
     * Creates new form VentanaAdicionarConceptos
     */
    public VentanaAdicionarConceptos(ventanaConsultarF vf, int fila, ArrayList<String> Listaconceptos) {
        initComponents();
        Utilidades.EstablecerIcono(this);
        this.vf = vf;
        this.setLocationRelativeTo(null);
        lblIdentificacion.setText(""+vf.lblDocumento.getText());
        lblIdentificacion.setVisible(false);
        lblIdConcepto.setVisible(false);
        lblTipoConcepto.setVisible(false);
        lblDescripcionConcepto.setVisible(false);
        lblId_Tratamiento.setVisible(false);
        lblId_Tratamiento.setText("");
        this.fila = fila;
        this.Listaconceptos = Listaconceptos;
        txtCantidad.setEnabled(true);
        txtValorU.setEnabled(true);
        txtValorT.setEnabled(false);
        
        if(fila >= 0){
            LlenarFormulario();
        }else{
            EstadoFormulario(0);
            LimpiarFormulario();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblBsqConcepto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtConcepto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblIdConcepto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtValorU = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtValorT = new javax.swing.JTextField();
        btnDescartar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblDescripcionConcepto = new javax.swing.JLabel();
        lblIdentificacion = new javax.swing.JLabel();
        lblTipoConcepto = new javax.swing.JLabel();
        lblId_Tratamiento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Concepto");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(26, 82, 118), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(26, 82, 118));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/cerrar_1.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/minimizar.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Agregar Concepto");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 30));

        lblBsqConcepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/lupa_1.png"))); // NOI18N
        lblBsqConcepto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBsqConceptoMouseClicked(evt);
            }
        });
        jPanel1.add(lblBsqConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 30, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 360, 10));

        txtConcepto.setEditable(false);
        txtConcepto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtConcepto.setForeground(new java.awt.Color(21, 67, 96));
        txtConcepto.setBorder(null);
        jPanel1.add(txtConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 360, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 67, 96));
        jLabel2.setText("Valor Total");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        jPanel1.add(lblIdConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(21, 67, 96));
        jLabel3.setText("Concepto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(21, 67, 96));
        txtCantidad.setBorder(null);
        txtCantidad.setEnabled(false);
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
        });
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 70, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 70, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(21, 67, 96));
        jLabel4.setText("Cantidad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtValorU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtValorU.setForeground(new java.awt.Color(21, 67, 96));
        txtValorU.setBorder(null);
        txtValorU.setEnabled(false);
        txtValorU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorUKeyReleased(evt);
            }
        });
        jPanel1.add(txtValorU, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 170, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 170, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(21, 67, 96));
        jLabel5.setText("Valor Unitario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 170, 10));

        txtValorT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtValorT.setForeground(new java.awt.Color(21, 67, 96));
        txtValorT.setBorder(null);
        txtValorT.setEnabled(false);
        jPanel1.add(txtValorT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 170, 30));

        btnDescartar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar.png"))); // NOI18N
        btnDescartar.setToolTipText("Descartar");
        btnDescartar.setBorderPainted(false);
        btnDescartar.setContentAreaFilled(false);
        btnDescartar.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnDescartar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar_over.png"))); // NOI18N
        btnDescartar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar_over.png"))); // NOI18N
        btnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 64, 64));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_over.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_over.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 64, 64));
        jPanel1.add(lblDescripcionConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));
        jPanel1.add(lblIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));
        jPanel1.add(lblTipoConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));
        jPanel1.add(lblId_Tratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        this.setState(VentanaAdicionarConceptos.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        x = evt.getX();
        y = evt.getY();   
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        this.setLocation(this.getLocation().x + evt.getX()-x, this.getLocation().y + evt.getY()-y);
    }//GEN-LAST:event_jPanel5MouseDragged

    private void lblBsqConceptoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBsqConceptoMouseClicked
        if(banBQDConc == 0){
            //new ventanaBusquedaPaciente(1, "IDENTIFICACION:-:NOMBRE", estadoch, this);
            if(lblBsqConcepto.isEnabled()){
                new Busquedas.ventanaBusquedacConceptoFactura(this).setVisible(true);
            }
        }   
    }//GEN-LAST:event_lblBsqConceptoMouseClicked

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
        System.out.println("txtCantidad.getText()-->"+txtCantidad.getText());
        System.out.println("txtCantidad.getText().length()-->"+txtCantidad.getText().length());
        Expresiones.procesarSoloNumeros(txtCantidad);
        if(txtCantidad.getText().length()>=3){
            txtCantidad.setText(txtCantidad.getText().substring(0, 2));
        }
        totalPago();
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void txtValorUKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorUKeyReleased
        String valoru = txtValorU.getText();     
        if(!valoru.equals("")){
            String valorsin = valoru.indexOf(".")>-1?valoru.replace(".", ""):valoru;
            System.out.println("valorsin--->"+valorsin);
            String dato = Expresiones.procesarSoloNum(valorsin);
            if(dato.length()>=9){
                dato  = dato.substring(0, 9);
            }  
            dato = Utilidades.MascaraMoneda(dato);
            txtValorU.setText(dato);
            totalPago();
            EstadoFormulario(1);
        }else{
            totalPago();
            EstadoFormulario(0);
        }
    }//GEN-LAST:event_txtValorUKeyReleased

    private void btnDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescartarActionPerformed
        LimpiarFormulario();
    }//GEN-LAST:event_btnDescartarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed


        if(lblIdConcepto.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Por favor seleccione un concepto para realizar la operación.");
            return;
        }
        if(txtCantidad.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Por favor ingrese la cantidad.");
            return;
        }
        if(txtValorU.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Por favor ingrese el valor a cobrar.");
            return;
        }
        
        if(fila>=0){
            
            String[] datos = new String[]{lblIdConcepto.getText(), txtConcepto.getText(),
                lblDescripcionConcepto.getText(), txtCantidad.getText(), txtValorU.getText(),
                txtValorT.getText(), ""+lblTipoConcepto.getText(), "", lblId_Tratamiento.getText()};
            vf.datos = datos; 
            vf.ActualizarTablaConceptos(fila);
        }else{
            String[] datos = new String[]{lblIdConcepto.getText(), txtConcepto.getText(),
                lblDescripcionConcepto.getText(), txtCantidad.getText(), txtValorU.getText(),
                txtValorT.getText(), ""+lblTipoConcepto.getText(), "", lblId_Tratamiento.getText()};
            vf.datos = datos;
            vf.AgregarTablaConceptos();
        }
        
        this.dispose();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
        
    }//GEN-LAST:event_txtCantidadKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdicionarConceptos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdicionarConceptos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdicionarConceptos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdicionarConceptos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdicionarConceptos(null, -1, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblBsqConcepto;
    public javax.swing.JLabel lblDescripcionConcepto;
    public javax.swing.JLabel lblIdConcepto;
    public javax.swing.JLabel lblId_Tratamiento;
    public javax.swing.JLabel lblIdentificacion;
    public javax.swing.JLabel lblTipoConcepto;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtConcepto;
    public javax.swing.JTextField txtValorT;
    public javax.swing.JTextField txtValorU;
    // End of variables declaration//GEN-END:variables

    private void LimpiarFormulario() {
        lblIdConcepto.setText("");
        lblId_Tratamiento.setText("");
        txtConcepto.setText("");
        txtCantidad.setText("");
        txtValorU.setText("");
        txtValorT.setText("");
        
        
        
    }
    
    public void EstadoFormulario(int opcion){
        if(opcion == 0){//DESABILITO
            btnGuardar.setEnabled(false);
        }else{
            btnGuardar.setEnabled(true);
        }
    }

    public void totalPago() {
        String cant = txtCantidad.getText();
        String valoru = txtValorU.getText();
        
        int valort = (cant.equals("")?0:Integer.parseInt(cant)) * (valoru.equals("")?0:Integer.parseInt(valoru.replace(".", "")));
        txtValorT.setText(Utilidades.MascaraMoneda(""+valort));        
        
    }

    private void LlenarFormulario() {
        lblBsqConcepto.setEnabled(false);
        System.out.println("fila-->"+fila);
        // LISta Conceptos
        //0--> idconcepto, 1--> concepto, 2--> descripcion concepto
        //3--> cantidad, 4--> valorunico, 5--> Valor Total, 6--> tipoconcepto, 7-->Num Factura
        
        lblIdConcepto.setText(vf.ListaConceptos.get(fila)[0]);
        txtConcepto.setText(vf.ListaConceptos.get(fila)[1]);
        lblDescripcionConcepto.setText(vf.ListaConceptos.get(fila)[2]);
        txtCantidad.setText(vf.ListaConceptos.get(fila)[3]);
        txtValorU.setText(Utilidades.MascaraMoneda(vf.ListaConceptos.get(fila)[4].replace(".", "")));
        txtValorT.setText(Utilidades.MascaraMoneda(vf.ListaConceptos.get(fila)[5].replace(".", "")));
        lblId_Tratamiento.setText(vf.ListaConceptos.get(fila)[8]);
        lblTipoConcepto.setText(vf.ListaConceptos.get(fila)[6]);
        txtCantidad.setEnabled(true);
        txtValorU.setEnabled(true);
        totalPago();
        txtCantidad.requestFocus();
    }

}
